(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["styles"], {
  /***/
  "./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src/index.js?!./node_modules/sass-loader/dist/cjs.js?!./src/styles.scss":
  /*!********************************************************************************************************************************************************************************************************************!*\
    !*** ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/dist/cjs.js??ref--13-3!./src/styles.scss ***!
    \********************************************************************************************************************************************************************************************************************/

  /*! no static exports found */

  /***/
  function node_modulesAngularDevkitBuildAngularSrcAngularCliFilesPluginsRawCssLoaderJsNode_modulesPostcssLoaderSrcIndexJsNode_modulesSassLoaderDistCjsJsSrcStylesScss(module, exports) {
    module.exports = [[module.i, "/* http://meyerweb.com/eric/tools/css/reset/ \n   v2.0 | 20110126\n   License: none (public domain)\n*/\n/* Generated by Glyphter (http://www.glyphter.com) on  Sun Apr 19 2020*/\n@font-face {\n    font-family: 'icons';\n    src: url('icons.eot');\n    src: url('icons.eot?#iefix') format('embedded-opentype'),\n         url('icons.woff') format('woff'),\n         url('icons.ttf') format('truetype'),\n         url('icons.svg#icons') format('svg');\n    font-weight: normal;\n    font-style: normal;\n}\n[class*='icon-']:before{\n\tdisplay: inline-block;\n   font-family: 'icons';\n   font-style: normal;\n   font-weight: normal;\n   line-height: 1;\n   -webkit-font-smoothing: antialiased;\n   -moz-osx-font-smoothing: grayscale\n}\n.icon-facebook:before{content:'\\0041';}\n.icon-instagram:before{content:'\\0042';}\n.icon-linkedin:before{content:'\\0043';}\n.icon-twitter:before{content:'\\0044';}\n.icon-whatsapp:before{content:'\\0045';}\n.icon-logo_branco:before{content:'\\0046';}\n.icon-logo_preto:before{content:'\\0047';}\nhtml, body, div, span, applet, object, iframe,\nh1, h2, h3, h4, h5, h6, p, blockquote, pre,\na, abbr, acronym, address, big, cite, code,\ndel, dfn, em, img, ins, kbd, q, s, samp,\nsmall, strike, strong, sub, sup, tt, var,\nb, u, i, center,\ndl, dt, dd, ol, ul, li,\nfieldset, form, label, legend,\ntable, caption, tbody, tfoot, thead, tr, th, td,\narticle, aside, canvas, details, embed,\nfigure, figcaption, footer, header, hgroup,\nmenu, nav, output, ruby, section, summary,\ntime, mark, audio, video {\n  margin: 0;\n  padding: 0;\n  border: 0;\n  font-size: 100%;\n  font: inherit;\n  vertical-align: baseline;\n}\n/* HTML5 display-role reset for older browsers */\narticle, aside, details, figcaption, figure,\nfooter, header, hgroup, menu, nav, section {\n  display: block;\n}\nbody {\n  line-height: 1;\n}\nol, ul {\n  list-style: none;\n}\nblockquote, q {\n  quotes: none;\n}\nblockquote:before, blockquote:after,\nq:before, q:after {\n  content: \"\";\n  content: none;\n}\ntable {\n  border-collapse: collapse;\n  border-spacing: 0;\n}\nhtml,\nbody {\n  font-family: \"Montserrat\", sans-serif;\n  font-weight: 500;\n  color: #151522;\n  min-height: 100vh;\n  overflow: auto;\n}\n* {\n  box-sizing: border-box;\n  outline: none;\n}\nbody {\n  overflow: hidden;\n}\na {\n  text-decoration: none;\n  color: inherit;\n}\n.app-content {\n  padding: 15px 0;\n}\n@media (min-width: 576px) {\n  .app-content {\n    padding: 20px 0;\n  }\n}\n::-webkit-scrollbar {\n  width: 7px;\n}\n::-webkit-scrollbar-track {\n  background: #dddddd;\n  border-radius: 10px;\n}\n::-webkit-scrollbar-thumb {\n  background: #242424;\n  border-radius: 10px;\n}\n.container {\n  width: 100%;\n  margin: 0 auto;\n}\n@media (min-width: 768px) {\n  .container {\n    padding: 0 10px;\n    max-width: calc(768px + 100px);\n  }\n}\n@media (min-width: 992px) {\n  .container {\n    max-width: calc(992px + 100px);\n  }\n}\n@media (min-width: 1200px) {\n  .container {\n    max-width: calc(1200px + 100px);\n  }\n}\n@media (min-width: 1440px) {\n  .container {\n    max-width: calc(1440px + 100px);\n  }\n}\n.footer {\n  background: #151522;\n  color: white;\n}\n.footer > .wrapper {\n  padding: 50px 25px;\n  display: grid;\n  grid-template-columns: 1fr 1fr 1.7fr;\n  grid-gap: 70px;\n}\n.footer > .wrapper > .section > .title {\n  font-weight: 800;\n  margin-bottom: 25px;\n}\n.footer > .wrapper > .section > ul > li {\n  margin-bottom: 20px;\n  display: flex;\n  justify-content: space-between;\n}\n.menu {\n  height: 80px;\n  margin-bottom: 0;\n  box-shadow: 0px 4px 14px #0000001c;\n}\n@media (min-width: 768px) {\n  .menu {\n    margin-bottom: 15px;\n  }\n}\n@media (min-width: 1200px) {\n  .menu {\n    margin-bottom: 35px;\n  }\n}\n.menu > .wrapper {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  height: 100%;\n  position: relative;\n}\n.menu > .wrapper > .logo {\n  width: 120px;\n  margin-left: 20px;\n}\n.menu > .wrapper > .logo > .image {\n  width: 100%;\n}\n.menu > .wrapper > .links-desktop {\n  display: none;\n}\n@media (min-width: 576px) {\n  .menu > .wrapper > .links-desktop {\n    display: inline-block;\n  }\n}\n.menu > .wrapper > .links-desktop > .link {\n  padding: 20px 25px;\n}\n.menu > .wrapper > .links-desktop > .link.-active {\n  color: #0028ff;\n  font-weight: 800;\n}\n.menu > .wrapper > .menu-mobile {\n  cursor: pointer;\n}\n@media (min-width: 576px) {\n  .menu > .wrapper > .menu-mobile {\n    display: none;\n  }\n}\n.menu > .wrapper > .menu-mobile.-active > .links-mobile {\n  top: 70px;\n  opacity: 1;\n}\n.menu > .wrapper > .menu-mobile > .links-mobile {\n  display: flex;\n  flex-flow: column;\n  position: absolute;\n  left: 0;\n  transition: 1s;\n  top: -250px;\n  opacity: 0;\n  width: 100%;\n  background: white;\n  box-shadow: 0px 6px 17px #00000012;\n}\n.menu > .wrapper > .menu-mobile > .links-mobile > .link {\n  text-align: center;\n  padding: 30px 0;\n  border-top: 1px solid #f1f3f6;\n  background-color: white;\n  transition: background-color 0.2s;\n}\n.menu > .wrapper > .menu-mobile > .links-mobile > .link:hover {\n  background-color: #00000005;\n}\n.home > .start {\n  display: flex;\n  flex-flow: column;\n}\n@media (min-width: 1200px) {\n  .home > .start {\n    flex-flow: row;\n  }\n}\n.home > .start > .main {\n  padding: 5px 10px;\n}\n@media (min-width: 576px) {\n  .home > .start > .main {\n    padding: 20px;\n  }\n}\n@media (min-width: 1200px) {\n  .home > .start > .main {\n    flex: 1;\n  }\n}\n.home > .start > .main > .title-subtitle > .title {\n  font-size: 30px;\n  line-height: 30px;\n  margin-bottom: 10px;\n  font-weight: 800;\n}\n@media (min-width: 768px) {\n  .home > .start > .main > .title-subtitle > .title {\n    font-size: 35px;\n    line-height: 35px;\n    margin-bottom: 15px;\n  }\n}\n@media (min-width: 1200px) {\n  .home > .start > .main > .title-subtitle > .title {\n    font-size: 42px;\n    line-height: 40px;\n    margin-bottom: 25px;\n  }\n}\n.home > .start > .main > .title-subtitle > .subtitle {\n  font-size: 15px;\n  color: #8A8A90;\n}\n@media (min-width: 768px) {\n  .home > .start > .main > .title-subtitle > .subtitle {\n    font-size: 18px;\n  }\n}\n@media (min-width: 1200px) {\n  .home > .start > .main > .title-subtitle > .subtitle {\n    font-size: 21px;\n  }\n}\n.home > .start > .main > .small-cards {\n  display: grid;\n  grid-template-columns: 1fr;\n  grid-template-rows: 1fr 1fr 1fr;\n  justify-items: stretch;\n  align-items: stretch;\n  margin: 15px 0;\n  grid-column-gap: 10px;\n  grid-row-gap: 20px;\n}\n@media (min-width: 576px) {\n  .home > .start > .main > .small-cards {\n    grid-template-columns: 1fr 1fr;\n  }\n}\n@media (min-width: 1200px) {\n  .home > .start > .main > .small-cards {\n    grid-column-gap: 40px;\n    grid-row-gap: 40px;\n    margin: 50px 0;\n  }\n}\n.home > .start > .main > .small-cards > .card {\n  display: flex;\n  align-items: center;\n  padding: 5px;\n}\n.home > .start > .main > .small-cards > .card > .thumbnail {\n  width: 155px;\n  margin-right: 25px;\n}\n.home > .start > .main > .small-cards > .card > .thumbnail > .image {\n  width: 100%;\n}\n.home > .start > .main > .small-cards > .card > .info {\n  width: 100%;\n}\n.home > .start > .main > .small-cards > .card > .info > .title {\n  font-weight: 800;\n  font-size: 21px;\n  margin-bottom: 5px;\n}\n.home > .start > .main > .small-cards > .card > .info > .description {\n  font-weight: 500;\n  font-size: 13px;\n  margin-top: 5px;\n  line-height: 20px;\n}\n.home > .start > .main > .small-cards > .card > .info > .link {\n  width: calc(100% - 40px);\n  display: inline-block;\n  text-align: right;\n  margin-top: 25px;\n  font-size: 11px;\n  color: #0028ff;\n}\n.home > .start > .aside {\n  padding: 15px;\n}\n@media (min-width: 1200px) {\n  .home > .start > .aside {\n    padding: 20px;\n    width: 470px;\n  }\n}\n.home > .start > .aside > .aside-cards {\n  display: flex;\n  flex-flow: column;\n}\n.home > .start > .aside > .aside-cards > .card {\n  height: 300px;\n  background: #dadada;\n  position: relative;\n  overflow: hidden;\n  cursor: pointer;\n}\n@media (min-width: 1200px) {\n  .home > .start > .aside > .aside-cards > .card {\n    height: 410px;\n  }\n}\n.home > .start > .aside > .aside-cards > .card:hover > .background-img {\n  transform: scale(1.1) translateY(-45%);\n}\n.home > .start > .aside > .aside-cards > .card > .background-img {\n  top: 50%;\n  transform: translateY(-50%);\n  position: absolute;\n  width: 100%;\n  min-height: 100%;\n  z-index: 1;\n  transition: transform 0.2s;\n}\n.home > .start > .aside > .aside-cards > .card > .read-more {\n  position: absolute;\n  z-index: 3;\n  bottom: 0;\n  right: 0;\n  color: white;\n  font-size: 11px;\n  padding: 10px 20px;\n}\n@media (min-width: 1200px) {\n  .home > .start > .aside > .aside-cards > .card > .read-more {\n    font-size: inherit;\n  }\n}\n.home > .start > .aside > .aside-cards > .card > .title-description {\n  position: absolute;\n  z-index: 2;\n  color: white;\n  width: 100%;\n  bottom: 0;\n  padding: 20px 15px 30px 15px;\n  background: #000000b8;\n}\n@media (min-width: 1200px) {\n  .home > .start > .aside > .aside-cards > .card > .title-description {\n    padding: 30px 20px 40px 20px;\n  }\n}\n.home > .start > .aside > .aside-cards > .card > .title-description > .title {\n  font-size: 27px;\n  font-weight: 800;\n  margin-bottom: 5px;\n}\n@media (min-width: 1200px) {\n  .home > .start > .aside > .aside-cards > .card > .title-description > .title {\n    margin-bottom: 15px;\n    font-size: 34px;\n  }\n}\n.home > .start > .aside > .aside-cards > .card > .title-description > .description {\n  font-size: 15px;\n  line-height: 20px;\n}\n@media (min-width: 1200px) {\n  .home > .start > .aside > .aside-cards > .card > .title-description > .description {\n    font-size: 13px;\n    line-height: 30px;\n  }\n}\n.btn {\n  background: #0028ff;\n  color: white;\n  font-size: 24px;\n  text-align: left;\n  max-width: 300px;\n  font-weight: 800;\n  border: none;\n  border-radius: 3px;\n  padding: 15px 30px;\n  transition: 0.2s;\n  cursor: pointer;\n}\n.btn:hover {\n  background: #0024e6;\n}\n.guide-detail {\n  padding: 10px 15px;\n}\n@media (min-width: 1200px) {\n  .guide-detail {\n    padding: 50px 15%;\n  }\n}\n.guide-detail > .header > .title {\n  font-size: 30px;\n  line-height: 30px;\n  margin-bottom: 10px;\n  font-weight: 800;\n}\n@media (min-width: 768px) {\n  .guide-detail > .header > .title {\n    font-size: 35px;\n    line-height: 35px;\n    margin-bottom: 15px;\n  }\n}\n@media (min-width: 1200px) {\n  .guide-detail > .header > .title {\n    font-size: 42px;\n    line-height: 40px;\n    margin-bottom: 25px;\n  }\n}\n.guide-detail > .header > .subtitle {\n  font-size: 15px;\n  color: #8A8A90;\n  text-transform: uppercase;\n  margin-bottom: 5px;\n}\n@media (min-width: 768px) {\n  .guide-detail > .header > .subtitle {\n    font-size: 18px;\n    margin-bottom: 10px;\n  }\n}\n@media (min-width: 1200px) {\n  .guide-detail > .header > .subtitle {\n    font-size: 21px;\n    margin-bottom: 20px;\n  }\n}\n.guide-detail > .header > .time {\n  font-size: 13px;\n  color: #8A8A90;\n}\n@media (min-width: 768px) {\n  .guide-detail > .header > .time {\n    font-size: 15px;\n  }\n}\n@media (min-width: 1200px) {\n  .guide-detail > .header > .time {\n    font-size: 18px;\n  }\n}\n.guide-detail > .upper-thumb {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  margin: 30px 0 30px 0;\n}\n.guide-detail > .upper-thumb > .listen {\n  font-size: 20px;\n  display: flex;\n  align-items: center;\n  color: #0024e6;\n  transition: color 0.2s;\n  cursor: pointer;\n}\n.guide-detail > .upper-thumb > .listen:hover {\n  color: #001899;\n}\n.guide-detail > .upper-thumb > .listen > .text {\n  font-weight: 600;\n  margin-right: 10px;\n}\n.guide-detail > .upper-thumb > .listen > .play {\n  font-size: 28px;\n}\n.guide-detail > .upper-thumb > .share {\n  font-size: 28px;\n}\n.guide-detail > .upper-thumb > .share > .icon {\n  margin-left: 10px;\n  transition: color 0.2s;\n}\n.guide-detail > .upper-thumb > .share > .icon:hover {\n  color: #0028ff;\n}\n.guide-detail > .thumb {\n  margin-top: 20px;\n  margin-bottom: 20px;\n}\n.guide-detail > .thumb > .img-wrapper {\n  position: relative;\n  height: 250px;\n  overflow: hidden;\n}\n.guide-detail > .thumb > .img-wrapper > .img {\n  top: 50%;\n  transform: translateY(-50%);\n  position: absolute;\n  width: 100%;\n  min-height: 100%;\n}\n.guide-detail > .thumb > .description {\n  margin-top: 7px;\n  font-size: 13px;\n  color: #8A8A90;\n}\n.guide-detail .small-title {\n  font-size: 22px;\n  font-weight: 800;\n  margin-bottom: 25px;\n  margin-top: 50px;\n}\n.guide-detail > .references .link {\n  color: #0028ff;\n  display: inline-block;\n  margin-bottom: 15px;\n  cursor: pointer;\n  font-size: 12px;\n}\n.guide-detail > .guide > .paragraph {\n  line-height: 26px;\n  margin-bottom: 20px;\n}\n.guide-detail > .guide > .paragraph.-is-step {\n  margin-bottom: 0;\n}\n.guide-detail > .guide > .paragraph.-is-last-step {\n  margin-bottom: 20px;\n}\n.guide-detail > .guide > .paragraph > .step {\n  font-weight: 800;\n  color: #0028ff;\n  font-size: 20px;\n  margin-right: 5px;\n}\n.guide-detail > .share-next {\n  display: flex;\n  justify-content: space-between;\n  align-items: flex-start;\n  margin-top: 30px;\n}\n.guide-detail > .share-next > .share > .small-title {\n  margin-top: 0;\n}\n._text-center {\n  text-align: center;\n}\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9DOlxcVXNlcnNcXFRha2FyYVxcR29vZ2xlIERyaXZlXFxQcm9qZXRvc1xcOGRvYmVtL3NyY1xcc3R5bGVzXFxyZXNldC5zY3NzIiwic3JjL2Fzc2V0cy9ncmx5cGh0ZXItZm9udC9jc3MvaWNvbnMuY3NzIiwic3JjL3N0eWxlcy5zY3NzIiwic3JjL0M6XFxVc2Vyc1xcVGFrYXJhXFxHb29nbGUgRHJpdmVcXFByb2pldG9zXFw4ZG9iZW0vc3JjXFxzdHlsZXNcXHNldHVwLnNjc3MiLCJzcmMvQzpcXFVzZXJzXFxUYWthcmFcXEdvb2dsZSBEcml2ZVxcUHJvamV0b3NcXDhkb2JlbS9zcmNcXHN0eWxlc1xcdmFyaWFibGVzLnNjc3MiLCJzcmMvQzpcXFVzZXJzXFxUYWthcmFcXEdvb2dsZSBEcml2ZVxcUHJvamV0b3NcXDhkb2JlbS9zcmNcXHN0eWxlc1xcZm9vdGVyLnNjc3MiLCJzcmMvQzpcXFVzZXJzXFxUYWthcmFcXEdvb2dsZSBEcml2ZVxcUHJvamV0b3NcXDhkb2JlbS9zcmNcXHN0eWxlc1xcbWVudS5zY3NzIiwic3JjL0M6XFxVc2Vyc1xcVGFrYXJhXFxHb29nbGUgRHJpdmVcXFByb2pldG9zXFw4ZG9iZW0vc3JjXFxzdHlsZXNcXGhvbWUuc2NzcyIsInNyYy9DOlxcVXNlcnNcXFRha2FyYVxcR29vZ2xlIERyaXZlXFxQcm9qZXRvc1xcOGRvYmVtL3NyY1xcc3R5bGVzXFxidXR0b25zLnNjc3MiLCJzcmMvQzpcXFVzZXJzXFxUYWthcmFcXEdvb2dsZSBEcml2ZVxcUHJvamV0b3NcXDhkb2JlbS9zcmNcXHN0eWxlc1xcZ3VpZGUtZGV0YWlsLnNjc3MiLCJzcmMvQzpcXFVzZXJzXFxUYWthcmFcXEdvb2dsZSBEcml2ZVxcUHJvamV0b3NcXDhkb2JlbS9zcmNcXHN0eWxlc1xcdHJ1bXBzLnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7OztDQUFBO0FDQUEsdUVBQXVFO0FBQ3ZFO0lBQ0ksb0JBQW9CO0lBQ3BCLHFCQUE4QjtJQUM5Qjs7OzZDQUdrRDtJQUNsRCxtQkFBbUI7SUFDbkIsa0JBQWtCO0FBQ3RCO0FBQ0E7Q0FDQyxxQkFBcUI7R0FDbkIsb0JBQW9CO0dBQ3BCLGtCQUFrQjtHQUNsQixtQkFBbUI7R0FDbkIsY0FBYztHQUNkLG1DQUFtQztHQUNuQztBQUNIO0FBQ0Esc0JBQXNCLGVBQWUsQ0FBQztBQUN0Qyx1QkFBdUIsZUFBZSxDQUFDO0FBQ3ZDLHNCQUFzQixlQUFlLENBQUM7QUFDdEMscUJBQXFCLGVBQWUsQ0FBQztBQUNyQyxzQkFBc0IsZUFBZSxDQUFDO0FBQ3RDLHlCQUF5QixlQUFlLENBQUM7QUFDekMsd0JBQXdCLGVBQWUsQ0FBQztBRHJCeEM7Ozs7Ozs7Ozs7Ozs7RUFhQyxTQUFBO0VBQ0EsVUFBQTtFQUNBLFNBQUE7RUFDQSxlQUFBO0VBQ0EsYUFBQTtFQUNBLHdCQUFBO0FFQ0Q7QUZDQSxnREFBQTtBQUNBOztFQUVDLGNBQUE7QUVFRDtBRkFBO0VBQ0MsY0FBQTtBRUdEO0FGREE7RUFDQyxnQkFBQTtBRUlEO0FGRkE7RUFDQyxZQUFBO0FFS0Q7QUZIQTs7RUFFQyxXQUFBO0VBQ0EsYUFBQTtBRU1EO0FGSkE7RUFDQyx5QkFBQTtFQUNBLGlCQUFBO0FFT0Q7QUNyREE7O0VBRUUscUNBQUE7RUFDQSxnQkFBQTtFQUNBLGNDR2dCO0VERmhCLGlCQUFBO0VBQ0EsY0FBQTtBRHdERjtBQ3JEQTtFQUNFLHNCQUFBO0VBQ0EsYUFBQTtBRHdERjtBQ3JEQTtFQUNFLGdCQUFBO0FEd0RGO0FDckRBO0VBQ0UscUJBQUE7RUFDQSxjQUFBO0FEd0RGO0FDckRBO0VBQ0UsZUFBQTtBRHdERjtBQ3RERTtFQUhGO0lBSUksZUFBQTtFRHlERjtBQUNGO0FDdERBO0VBQ0UsVUFBQTtBRHlERjtBQ3REQTtFQUNFLG1CQUFBO0VBQ0EsbUJBQUE7QUR5REY7QUN0REE7RUFDRSxtQkFBQTtFQUNBLG1CQUFBO0FEeURGO0FDdERBO0VBQ0UsV0FBQTtFQUNBLGNBQUE7QUR5REY7QUN2REU7RUFKRjtJQUtJLGVBQUE7SUFDQSw4QkFBQTtFRDBERjtBQUNGO0FDeERFO0VBVEY7SUFVSSw4QkFBQTtFRDJERjtBQUNGO0FDekRFO0VBYkY7SUFjSSwrQkFBQTtFRDRERjtBQUNGO0FDMURFO0VBakJGO0lBa0JJLCtCQUFBO0VENkRGO0FBQ0Y7QUc3SEE7RUFDRSxtQkRNZ0I7RUNMaEIsWUFBQTtBSGdJRjtBRzlIRTtFQUNFLGtCQUFBO0VBQ0EsYUFBQTtFQUNBLG9DQUFBO0VBQ0EsY0FBQTtBSGdJSjtBRzVITTtFQUNFLGdCQUFBO0VBQ0EsbUJBQUE7QUg4SFI7QUcxSE07RUFDRSxtQkFBQTtFQUNBLGFBQUE7RUFDQSw4QkFBQTtBSDRIUjtBSWpKQTtFQUNFLFlBQUE7RUFDQSxnQkFBQTtFQUNBLGtDQUFBO0FKb0pGO0FJbEpFO0VBTEY7SUFNSSxtQkFBQTtFSnFKRjtBQUNGO0FJbkpFO0VBVEY7SUFVSSxtQkFBQTtFSnNKRjtBQUNGO0FJcEpFO0VBQ0UsYUFBQTtFQUNBLDhCQUFBO0VBQ0EsbUJBQUE7RUFDQSxZQUFBO0VBQ0Esa0JBQUE7QUpzSko7QUlwSkk7RUFDRSxZQUFBO0VBQ0EsaUJBQUE7QUpzSk47QUlwSk07RUFDRSxXQUFBO0FKc0pSO0FJbEpJO0VBQ0UsYUFBQTtBSm9KTjtBSWxKTTtFQUhGO0lBSUkscUJBQUE7RUpxSk47QUFDRjtBSW5KTTtFQUNFLGtCQUFBO0FKcUpSO0FJbkpRO0VBQ0UsY0ZsQ007RUVtQ04sZ0JBQUE7QUpxSlY7QUloSkk7RUFDRSxlQUFBO0FKa0pOO0FJaEpNO0VBSEY7SUFJSSxhQUFBO0VKbUpOO0FBQ0Y7QUloSlE7RUFDRSxTQUFBO0VBQ0EsVUFBQTtBSmtKVjtBSTlJTTtFQUNFLGFBQUE7RUFDQSxpQkFBQTtFQUNBLGtCQUFBO0VBQ0EsT0FBQTtFQUNBLGNBQUE7RUFDQSxXQUFBO0VBQ0EsVUFBQTtFQUNBLFdBQUE7RUFDQSxpQkFBQTtFQUNBLGtDQUFBO0FKZ0pSO0FJOUlRO0VBQ0Usa0JBQUE7RUFDQSxlQUFBO0VBQ0EsNkJBQUE7RUFDQSx1QkFBQTtFQUNBLGlDQUFBO0FKZ0pWO0FJOUlVO0VBQ0UsMkJBQUE7QUpnSlo7QUsvTkU7RUFDRSxhQUFBO0VBQ0EsaUJBQUE7QUxrT0o7QUtoT0k7RUFKRjtJQUtJLGNBQUE7RUxtT0o7QUFDRjtBS2pPSTtFQUNFLGlCQUFBO0FMbU9OO0FLak9NO0VBSEY7SUFJSSxhQUFBO0VMb09OO0FBQ0Y7QUtsT007RUFQRjtJQVFJLE9BQUE7RUxxT047QUFDRjtBS2xPUTtFQUNFLGVBQUE7RUFDQSxpQkFBQTtFQUNBLG1CQUFBO0VBQ0EsZ0JBQUE7QUxvT1Y7QUtsT1U7RUFORjtJQU9JLGVBQUE7SUFDQSxpQkFBQTtJQUNBLG1CQUFBO0VMcU9WO0FBQ0Y7QUtuT1U7RUFaRjtJQWFJLGVBQUE7SUFDQSxpQkFBQTtJQUNBLG1CQUFBO0VMc09WO0FBQ0Y7QUtuT1E7RUFDRSxlQUFBO0VBQ0EsY0hsQ0c7QUZ1UWI7QUtuT1U7RUFKRjtJQUtJLGVBQUE7RUxzT1Y7QUFDRjtBS3BPVTtFQVJGO0lBU0ksZUFBQTtFTHVPVjtBQUNGO0FLbk9NO0VBQ0UsYUFBQTtFQUNBLDBCQUFBO0VBQ0EsK0JBQUE7RUFDQSxzQkFBQTtFQUNBLG9CQUFBO0VBQ0EsY0FBQTtFQUNBLHFCQUFBO0VBQ0Esa0JBQUE7QUxxT1I7QUtqT1E7RUFaRjtJQWFJLDhCQUFBO0VMb09SO0FBQ0Y7QUtsT1E7RUFoQkY7SUFpQkkscUJBQUE7SUFDQSxrQkFBQTtJQUNBLGNBQUE7RUxxT1I7QUFDRjtBS25PUTtFQUNFLGFBQUE7RUFDQSxtQkFBQTtFQUNBLFlBQUE7QUxxT1Y7QUtuT1U7RUFDRSxZQUFBO0VBQ0Esa0JBQUE7QUxxT1o7QUtuT1k7RUFDRSxXQUFBO0FMcU9kO0FLak9VO0VBQ0UsV0FBQTtBTG1PWjtBS2pPWTtFQUNFLGdCQUFBO0VBQ0EsZUFBQTtFQUNBLGtCQUFBO0FMbU9kO0FLaE9ZO0VBQ0UsZ0JBQUE7RUFDQSxlQUFBO0VBQ0EsZUFBQTtFQUNBLGlCQUFBO0FMa09kO0FLL05ZO0VBQ0Usd0JBQUE7RUFDQSxxQkFBQTtFQUNBLGlCQUFBO0VBQ0EsZ0JBQUE7RUFDQSxlQUFBO0VBQ0EsY0gxR0U7QUYyVWhCO0FLek5JO0VBQ0UsYUFBQTtBTDJOTjtBS3pOTTtFQUhGO0lBSUksYUFBQTtJQUNBLFlBQUE7RUw0Tk47QUFDRjtBSzFOTTtFQUVFLGFBQUE7RUFDQSxpQkFBQTtBTDJOUjtBS3pOUTtFQUNFLGFBQUE7RUFDQSxtQkFBQTtFQUNBLGtCQUFBO0VBQ0EsZ0JBQUE7RUFDQSxlQUFBO0FMMk5WO0FLek5VO0VBUEY7SUFRSSxhQUFBO0VMNE5WO0FBQ0Y7QUt6Tlk7RUFDRSxzQ0FBQTtBTDJOZDtBS3ZOVTtFQUNFLFFBQUE7RUFDQSwyQkFBQTtFQUNBLGtCQUFBO0VBQ0EsV0FBQTtFQUNBLGdCQUFBO0VBQ0EsVUFBQTtFQUNBLDBCQUFBO0FMeU5aO0FLdE5VO0VBQ0Usa0JBQUE7RUFDQSxVQUFBO0VBQ0EsU0FBQTtFQUNBLFFBQUE7RUFDQSxZQUFBO0VBQ0EsZUFBQTtFQUNBLGtCQUFBO0FMd05aO0FLdE5ZO0VBVEY7SUFVSSxrQkFBQTtFTHlOWjtBQUNGO0FLck5VO0VBQ0Usa0JBQUE7RUFDQSxVQUFBO0VBQ0EsWUFBQTtFQUNBLFdBQUE7RUFDQSxTQUFBO0VBQ0EsNEJBQUE7RUFDQSxxQkFBQTtBTHVOWjtBS3BOWTtFQVZGO0lBV0ksNEJBQUE7RUx1Tlo7QUFDRjtBS3BOWTtFQUNFLGVBQUE7RUFDQSxnQkFBQTtFQUNBLGtCQUFBO0FMc05kO0FLcE5jO0VBTEY7SUFNSSxtQkFBQTtJQUNBLGVBQUE7RUx1TmQ7QUFDRjtBS3BOWTtFQUNFLGVBQUE7RUFDQSxpQkFBQTtBTHNOZDtBS3BOYztFQUpGO0lBS0ksZUFBQTtJQUNBLGlCQUFBO0VMdU5kO0FBQ0Y7QU12YUE7RUFDSSxtQkpLWTtFSUpaLFlBQUE7RUFDQSxlQUFBO0VBQ0EsZ0JBQUE7RUFDQSxnQkFBQTtFQUNBLGdCQUFBO0VBQ0EsWUFBQTtFQUNBLGtCQUFBO0VBQ0Esa0JBQUE7RUFDQSxnQkFBQTtFQUNBLGVBQUE7QU4wYUo7QU14YUk7RUFDSSxtQkFBQTtBTjBhUjtBT3hiQTtFQUNFLGtCQUFBO0FQMmJGO0FPemJFO0VBSEY7SUFJSSxpQkFBQTtFUDRiRjtBQUNGO0FPemJJO0VBQ0UsZUFBQTtFQUNBLGlCQUFBO0VBQ0EsbUJBQUE7RUFDQSxnQkFBQTtBUDJiTjtBT3piTTtFQU5GO0lBT0ksZUFBQTtJQUNBLGlCQUFBO0lBQ0EsbUJBQUE7RVA0Yk47QUFDRjtBTzFiTTtFQVpGO0lBYUksZUFBQTtJQUNBLGlCQUFBO0lBQ0EsbUJBQUE7RVA2Yk47QUFDRjtBTzFiSTtFQUNFLGVBQUE7RUFDQSxjTHJCTztFS3NCUCx5QkFBQTtFQUNBLGtCQUFBO0FQNGJOO0FPMWJNO0VBTkY7SUFPSSxlQUFBO0lBQ0EsbUJBQUE7RVA2Yk47QUFDRjtBTzNiTTtFQVhGO0lBWUksZUFBQTtJQUNBLG1CQUFBO0VQOGJOO0FBQ0Y7QU8zYkk7RUFDRSxlQUFBO0VBQ0EsY0x0Q087QUZtZWI7QU8zYk07RUFKRjtJQUtJLGVBQUE7RVA4Yk47QUFDRjtBTzViTTtFQVJGO0lBU0ksZUFBQTtFUCtiTjtBQUNGO0FPM2JFO0VBQ0UsYUFBQTtFQUNBLDhCQUFBO0VBQ0EsbUJBQUE7RUFDQSxxQkFBQTtBUDZiSjtBTzNiSTtFQUNFLGVBQUE7RUFDQSxhQUFBO0VBQ0EsbUJBQUE7RUFDQSxjQUFBO0VBQ0Esc0JBQUE7RUFDQSxlQUFBO0FQNmJOO0FPM2JNO0VBQ0UsY0FBQTtBUDZiUjtBTzFiTTtFQUNFLGdCQUFBO0VBQ0Esa0JBQUE7QVA0YlI7QU96Yk07RUFDRSxlQUFBO0FQMmJSO0FPdmJJO0VBQ0UsZUFBQTtBUHliTjtBT3ZiTTtFQUNFLGlCQUFBO0VBRUYsc0JBQUE7QVB3Yk47QU90Yk07RUFDRSxjTHpGUTtBRmloQmhCO0FPbGJFO0VBQ0UsZ0JBQUE7RUFDQSxtQkFBQTtBUG9iSjtBT2xiSTtFQUNFLGtCQUFBO0VBQ0EsYUFBQTtFQUNBLGdCQUFBO0FQb2JOO0FPbGJNO0VBQ0UsUUFBQTtFQUNBLDJCQUFBO0VBQ0Esa0JBQUE7RUFDQSxXQUFBO0VBQ0EsZ0JBQUE7QVBvYlI7QU9oYkk7RUFDRSxlQUFBO0VBQ0EsZUFBQTtFQUNBLGNMbEhPO0FGb2lCYjtBTzlhRTtFQUNFLGVBQUE7RUFDQSxnQkFBQTtFQUNBLG1CQUFBO0VBQ0EsZ0JBQUE7QVBnYko7QU81YUk7RUFDRSxjTGpJVTtFS2tJVixxQkFBQTtFQUNBLG1CQUFBO0VBQ0EsZUFBQTtFQUNBLGVBQUE7QVA4YU47QU96YUk7RUFDRSxpQkFBQTtFQUNBLG1CQUFBO0FQMmFOO0FPemFNO0VBQ0UsZ0JBQUE7QVAyYVI7QU94YU07RUFDRSxtQkFBQTtBUDBhUjtBT3ZhTTtFQUNFLGdCQUFBO0VBQ0EsY0x4SlE7RUt5SlIsZUFBQTtFQUNBLGlCQUFBO0FQeWFSO0FPcGFFO0VBQ0UsYUFBQTtFQUNBLDhCQUFBO0VBQ0EsdUJBQUE7RUFDQSxnQkFBQTtBUHNhSjtBT25hSTtFQUNKLGFBQUE7QVBxYUE7QVFsbEJBO0VBQ0ksa0JBQUE7QVJxbEJKIiwiZmlsZSI6InNyYy9zdHlsZXMuc2NzcyIsInNvdXJjZXNDb250ZW50IjpbIi8qIGh0dHA6Ly9tZXllcndlYi5jb20vZXJpYy90b29scy9jc3MvcmVzZXQvIFxyXG4gICB2Mi4wIHwgMjAxMTAxMjZcclxuICAgTGljZW5zZTogbm9uZSAocHVibGljIGRvbWFpbilcclxuKi9cclxuXHJcbmh0bWwsIGJvZHksIGRpdiwgc3BhbiwgYXBwbGV0LCBvYmplY3QsIGlmcmFtZSxcclxuaDEsIGgyLCBoMywgaDQsIGg1LCBoNiwgcCwgYmxvY2txdW90ZSwgcHJlLFxyXG5hLCBhYmJyLCBhY3JvbnltLCBhZGRyZXNzLCBiaWcsIGNpdGUsIGNvZGUsXHJcbmRlbCwgZGZuLCBlbSwgaW1nLCBpbnMsIGtiZCwgcSwgcywgc2FtcCxcclxuc21hbGwsIHN0cmlrZSwgc3Ryb25nLCBzdWIsIHN1cCwgdHQsIHZhcixcclxuYiwgdSwgaSwgY2VudGVyLFxyXG5kbCwgZHQsIGRkLCBvbCwgdWwsIGxpLFxyXG5maWVsZHNldCwgZm9ybSwgbGFiZWwsIGxlZ2VuZCxcclxudGFibGUsIGNhcHRpb24sIHRib2R5LCB0Zm9vdCwgdGhlYWQsIHRyLCB0aCwgdGQsXHJcbmFydGljbGUsIGFzaWRlLCBjYW52YXMsIGRldGFpbHMsIGVtYmVkLCBcclxuZmlndXJlLCBmaWdjYXB0aW9uLCBmb290ZXIsIGhlYWRlciwgaGdyb3VwLCBcclxubWVudSwgbmF2LCBvdXRwdXQsIHJ1YnksIHNlY3Rpb24sIHN1bW1hcnksXHJcbnRpbWUsIG1hcmssIGF1ZGlvLCB2aWRlbyB7XHJcblx0bWFyZ2luOiAwO1xyXG5cdHBhZGRpbmc6IDA7XHJcblx0Ym9yZGVyOiAwO1xyXG5cdGZvbnQtc2l6ZTogMTAwJTtcclxuXHRmb250OiBpbmhlcml0O1xyXG5cdHZlcnRpY2FsLWFsaWduOiBiYXNlbGluZTtcclxufVxyXG4vKiBIVE1MNSBkaXNwbGF5LXJvbGUgcmVzZXQgZm9yIG9sZGVyIGJyb3dzZXJzICovXHJcbmFydGljbGUsIGFzaWRlLCBkZXRhaWxzLCBmaWdjYXB0aW9uLCBmaWd1cmUsIFxyXG5mb290ZXIsIGhlYWRlciwgaGdyb3VwLCBtZW51LCBuYXYsIHNlY3Rpb24ge1xyXG5cdGRpc3BsYXk6IGJsb2NrO1xyXG59XHJcbmJvZHkge1xyXG5cdGxpbmUtaGVpZ2h0OiAxO1xyXG59XHJcbm9sLCB1bCB7XHJcblx0bGlzdC1zdHlsZTogbm9uZTtcclxufVxyXG5ibG9ja3F1b3RlLCBxIHtcclxuXHRxdW90ZXM6IG5vbmU7XHJcbn1cclxuYmxvY2txdW90ZTpiZWZvcmUsIGJsb2NrcXVvdGU6YWZ0ZXIsXHJcbnE6YmVmb3JlLCBxOmFmdGVyIHtcclxuXHRjb250ZW50OiAnJztcclxuXHRjb250ZW50OiBub25lO1xyXG59XHJcbnRhYmxlIHtcclxuXHRib3JkZXItY29sbGFwc2U6IGNvbGxhcHNlO1xyXG5cdGJvcmRlci1zcGFjaW5nOiAwO1xyXG59XHJcbiIsIi8qIEdlbmVyYXRlZCBieSBHbHlwaHRlciAoaHR0cDovL3d3dy5nbHlwaHRlci5jb20pIG9uICBTdW4gQXByIDE5IDIwMjAqL1xuQGZvbnQtZmFjZSB7XG4gICAgZm9udC1mYW1pbHk6ICdpY29ucyc7XG4gICAgc3JjOiB1cmwoJy4uL2ZvbnRzL2ljb25zLmVvdCcpO1xuICAgIHNyYzogdXJsKCcuLi9mb250cy9pY29ucy5lb3Q/I2llZml4JykgZm9ybWF0KCdlbWJlZGRlZC1vcGVudHlwZScpLFxuICAgICAgICAgdXJsKCcuLi9mb250cy9pY29ucy53b2ZmJykgZm9ybWF0KCd3b2ZmJyksXG4gICAgICAgICB1cmwoJy4uL2ZvbnRzL2ljb25zLnR0ZicpIGZvcm1hdCgndHJ1ZXR5cGUnKSxcbiAgICAgICAgIHVybCgnLi4vZm9udHMvaWNvbnMuc3ZnI2ljb25zJykgZm9ybWF0KCdzdmcnKTtcbiAgICBmb250LXdlaWdodDogbm9ybWFsO1xuICAgIGZvbnQtc3R5bGU6IG5vcm1hbDtcbn1cbltjbGFzcyo9J2ljb24tJ106YmVmb3Jle1xuXHRkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG4gICBmb250LWZhbWlseTogJ2ljb25zJztcbiAgIGZvbnQtc3R5bGU6IG5vcm1hbDtcbiAgIGZvbnQtd2VpZ2h0OiBub3JtYWw7XG4gICBsaW5lLWhlaWdodDogMTtcbiAgIC13ZWJraXQtZm9udC1zbW9vdGhpbmc6IGFudGlhbGlhc2VkO1xuICAgLW1vei1vc3gtZm9udC1zbW9vdGhpbmc6IGdyYXlzY2FsZVxufVxuLmljb24tZmFjZWJvb2s6YmVmb3Jle2NvbnRlbnQ6J1xcMDA0MSc7fVxuLmljb24taW5zdGFncmFtOmJlZm9yZXtjb250ZW50OidcXDAwNDInO31cbi5pY29uLWxpbmtlZGluOmJlZm9yZXtjb250ZW50OidcXDAwNDMnO31cbi5pY29uLXR3aXR0ZXI6YmVmb3Jle2NvbnRlbnQ6J1xcMDA0NCc7fVxuLmljb24td2hhdHNhcHA6YmVmb3Jle2NvbnRlbnQ6J1xcMDA0NSc7fVxuLmljb24tbG9nb19icmFuY286YmVmb3Jle2NvbnRlbnQ6J1xcMDA0Nic7fVxuLmljb24tbG9nb19wcmV0bzpiZWZvcmV7Y29udGVudDonXFwwMDQ3Jzt9IiwiLyogaHR0cDovL21leWVyd2ViLmNvbS9lcmljL3Rvb2xzL2Nzcy9yZXNldC8gXG4gICB2Mi4wIHwgMjAxMTAxMjZcbiAgIExpY2Vuc2U6IG5vbmUgKHB1YmxpYyBkb21haW4pXG4qL1xuQGltcG9ydCAnLi9hc3NldHMvZ3JseXBodGVyLWZvbnQvY3NzL2ljb25zLmNzcyc7XG5odG1sLCBib2R5LCBkaXYsIHNwYW4sIGFwcGxldCwgb2JqZWN0LCBpZnJhbWUsXG5oMSwgaDIsIGgzLCBoNCwgaDUsIGg2LCBwLCBibG9ja3F1b3RlLCBwcmUsXG5hLCBhYmJyLCBhY3JvbnltLCBhZGRyZXNzLCBiaWcsIGNpdGUsIGNvZGUsXG5kZWwsIGRmbiwgZW0sIGltZywgaW5zLCBrYmQsIHEsIHMsIHNhbXAsXG5zbWFsbCwgc3RyaWtlLCBzdHJvbmcsIHN1Yiwgc3VwLCB0dCwgdmFyLFxuYiwgdSwgaSwgY2VudGVyLFxuZGwsIGR0LCBkZCwgb2wsIHVsLCBsaSxcbmZpZWxkc2V0LCBmb3JtLCBsYWJlbCwgbGVnZW5kLFxudGFibGUsIGNhcHRpb24sIHRib2R5LCB0Zm9vdCwgdGhlYWQsIHRyLCB0aCwgdGQsXG5hcnRpY2xlLCBhc2lkZSwgY2FudmFzLCBkZXRhaWxzLCBlbWJlZCxcbmZpZ3VyZSwgZmlnY2FwdGlvbiwgZm9vdGVyLCBoZWFkZXIsIGhncm91cCxcbm1lbnUsIG5hdiwgb3V0cHV0LCBydWJ5LCBzZWN0aW9uLCBzdW1tYXJ5LFxudGltZSwgbWFyaywgYXVkaW8sIHZpZGVvIHtcbiAgbWFyZ2luOiAwO1xuICBwYWRkaW5nOiAwO1xuICBib3JkZXI6IDA7XG4gIGZvbnQtc2l6ZTogMTAwJTtcbiAgZm9udDogaW5oZXJpdDtcbiAgdmVydGljYWwtYWxpZ246IGJhc2VsaW5lO1xufVxuXG4vKiBIVE1MNSBkaXNwbGF5LXJvbGUgcmVzZXQgZm9yIG9sZGVyIGJyb3dzZXJzICovXG5hcnRpY2xlLCBhc2lkZSwgZGV0YWlscywgZmlnY2FwdGlvbiwgZmlndXJlLFxuZm9vdGVyLCBoZWFkZXIsIGhncm91cCwgbWVudSwgbmF2LCBzZWN0aW9uIHtcbiAgZGlzcGxheTogYmxvY2s7XG59XG5cbmJvZHkge1xuICBsaW5lLWhlaWdodDogMTtcbn1cblxub2wsIHVsIHtcbiAgbGlzdC1zdHlsZTogbm9uZTtcbn1cblxuYmxvY2txdW90ZSwgcSB7XG4gIHF1b3Rlczogbm9uZTtcbn1cblxuYmxvY2txdW90ZTpiZWZvcmUsIGJsb2NrcXVvdGU6YWZ0ZXIsXG5xOmJlZm9yZSwgcTphZnRlciB7XG4gIGNvbnRlbnQ6IFwiXCI7XG4gIGNvbnRlbnQ6IG5vbmU7XG59XG5cbnRhYmxlIHtcbiAgYm9yZGVyLWNvbGxhcHNlOiBjb2xsYXBzZTtcbiAgYm9yZGVyLXNwYWNpbmc6IDA7XG59XG5cbmh0bWwsXG5ib2R5IHtcbiAgZm9udC1mYW1pbHk6IFwiTW9udHNlcnJhdFwiLCBzYW5zLXNlcmlmO1xuICBmb250LXdlaWdodDogNTAwO1xuICBjb2xvcjogIzE1MTUyMjtcbiAgbWluLWhlaWdodDogMTAwdmg7XG4gIG92ZXJmbG93OiBhdXRvO1xufVxuXG4qIHtcbiAgYm94LXNpemluZzogYm9yZGVyLWJveDtcbiAgb3V0bGluZTogbm9uZTtcbn1cblxuYm9keSB7XG4gIG92ZXJmbG93OiBoaWRkZW47XG59XG5cbmEge1xuICB0ZXh0LWRlY29yYXRpb246IG5vbmU7XG4gIGNvbG9yOiBpbmhlcml0O1xufVxuXG4uYXBwLWNvbnRlbnQge1xuICBwYWRkaW5nOiAxNXB4IDA7XG59XG5AbWVkaWEgKG1pbi13aWR0aDogNTc2cHgpIHtcbiAgLmFwcC1jb250ZW50IHtcbiAgICBwYWRkaW5nOiAyMHB4IDA7XG4gIH1cbn1cblxuOjotd2Via2l0LXNjcm9sbGJhciB7XG4gIHdpZHRoOiA3cHg7XG59XG5cbjo6LXdlYmtpdC1zY3JvbGxiYXItdHJhY2sge1xuICBiYWNrZ3JvdW5kOiAjZGRkZGRkO1xuICBib3JkZXItcmFkaXVzOiAxMHB4O1xufVxuXG46Oi13ZWJraXQtc2Nyb2xsYmFyLXRodW1iIHtcbiAgYmFja2dyb3VuZDogIzI0MjQyNDtcbiAgYm9yZGVyLXJhZGl1czogMTBweDtcbn1cblxuLmNvbnRhaW5lciB7XG4gIHdpZHRoOiAxMDAlO1xuICBtYXJnaW46IDAgYXV0bztcbn1cbkBtZWRpYSAobWluLXdpZHRoOiA3NjhweCkge1xuICAuY29udGFpbmVyIHtcbiAgICBwYWRkaW5nOiAwIDEwcHg7XG4gICAgbWF4LXdpZHRoOiBjYWxjKDc2OHB4ICsgMTAwcHgpO1xuICB9XG59XG5AbWVkaWEgKG1pbi13aWR0aDogOTkycHgpIHtcbiAgLmNvbnRhaW5lciB7XG4gICAgbWF4LXdpZHRoOiBjYWxjKDk5MnB4ICsgMTAwcHgpO1xuICB9XG59XG5AbWVkaWEgKG1pbi13aWR0aDogMTIwMHB4KSB7XG4gIC5jb250YWluZXIge1xuICAgIG1heC13aWR0aDogY2FsYygxMjAwcHggKyAxMDBweCk7XG4gIH1cbn1cbkBtZWRpYSAobWluLXdpZHRoOiAxNDQwcHgpIHtcbiAgLmNvbnRhaW5lciB7XG4gICAgbWF4LXdpZHRoOiBjYWxjKDE0NDBweCArIDEwMHB4KTtcbiAgfVxufVxuXG4uZm9vdGVyIHtcbiAgYmFja2dyb3VuZDogIzE1MTUyMjtcbiAgY29sb3I6IHdoaXRlO1xufVxuLmZvb3RlciA+IC53cmFwcGVyIHtcbiAgcGFkZGluZzogNTBweCAyNXB4O1xuICBkaXNwbGF5OiBncmlkO1xuICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDFmciAxZnIgMS43ZnI7XG4gIGdyaWQtZ2FwOiA3MHB4O1xufVxuLmZvb3RlciA+IC53cmFwcGVyID4gLnNlY3Rpb24gPiAudGl0bGUge1xuICBmb250LXdlaWdodDogODAwO1xuICBtYXJnaW4tYm90dG9tOiAyNXB4O1xufVxuLmZvb3RlciA+IC53cmFwcGVyID4gLnNlY3Rpb24gPiB1bCA+IGxpIHtcbiAgbWFyZ2luLWJvdHRvbTogMjBweDtcbiAgZGlzcGxheTogZmxleDtcbiAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xufVxuXG4ubWVudSB7XG4gIGhlaWdodDogODBweDtcbiAgbWFyZ2luLWJvdHRvbTogMDtcbiAgYm94LXNoYWRvdzogMHB4IDRweCAxNHB4ICMwMDAwMDAxYztcbn1cbkBtZWRpYSAobWluLXdpZHRoOiA3NjhweCkge1xuICAubWVudSB7XG4gICAgbWFyZ2luLWJvdHRvbTogMTVweDtcbiAgfVxufVxuQG1lZGlhIChtaW4td2lkdGg6IDEyMDBweCkge1xuICAubWVudSB7XG4gICAgbWFyZ2luLWJvdHRvbTogMzVweDtcbiAgfVxufVxuLm1lbnUgPiAud3JhcHBlciB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2VlbjtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgaGVpZ2h0OiAxMDAlO1xuICBwb3NpdGlvbjogcmVsYXRpdmU7XG59XG4ubWVudSA+IC53cmFwcGVyID4gLmxvZ28ge1xuICB3aWR0aDogMTIwcHg7XG4gIG1hcmdpbi1sZWZ0OiAyMHB4O1xufVxuLm1lbnUgPiAud3JhcHBlciA+IC5sb2dvID4gLmltYWdlIHtcbiAgd2lkdGg6IDEwMCU7XG59XG4ubWVudSA+IC53cmFwcGVyID4gLmxpbmtzLWRlc2t0b3Age1xuICBkaXNwbGF5OiBub25lO1xufVxuQG1lZGlhIChtaW4td2lkdGg6IDU3NnB4KSB7XG4gIC5tZW51ID4gLndyYXBwZXIgPiAubGlua3MtZGVza3RvcCB7XG4gICAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICB9XG59XG4ubWVudSA+IC53cmFwcGVyID4gLmxpbmtzLWRlc2t0b3AgPiAubGluayB7XG4gIHBhZGRpbmc6IDIwcHggMjVweDtcbn1cbi5tZW51ID4gLndyYXBwZXIgPiAubGlua3MtZGVza3RvcCA+IC5saW5rLi1hY3RpdmUge1xuICBjb2xvcjogIzAwMjhmZjtcbiAgZm9udC13ZWlnaHQ6IDgwMDtcbn1cbi5tZW51ID4gLndyYXBwZXIgPiAubWVudS1tb2JpbGUge1xuICBjdXJzb3I6IHBvaW50ZXI7XG59XG5AbWVkaWEgKG1pbi13aWR0aDogNTc2cHgpIHtcbiAgLm1lbnUgPiAud3JhcHBlciA+IC5tZW51LW1vYmlsZSB7XG4gICAgZGlzcGxheTogbm9uZTtcbiAgfVxufVxuLm1lbnUgPiAud3JhcHBlciA+IC5tZW51LW1vYmlsZS4tYWN0aXZlID4gLmxpbmtzLW1vYmlsZSB7XG4gIHRvcDogNzBweDtcbiAgb3BhY2l0eTogMTtcbn1cbi5tZW51ID4gLndyYXBwZXIgPiAubWVudS1tb2JpbGUgPiAubGlua3MtbW9iaWxlIHtcbiAgZGlzcGxheTogZmxleDtcbiAgZmxleC1mbG93OiBjb2x1bW47XG4gIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgbGVmdDogMDtcbiAgdHJhbnNpdGlvbjogMXM7XG4gIHRvcDogLTI1MHB4O1xuICBvcGFjaXR5OiAwO1xuICB3aWR0aDogMTAwJTtcbiAgYmFja2dyb3VuZDogd2hpdGU7XG4gIGJveC1zaGFkb3c6IDBweCA2cHggMTdweCAjMDAwMDAwMTI7XG59XG4ubWVudSA+IC53cmFwcGVyID4gLm1lbnUtbW9iaWxlID4gLmxpbmtzLW1vYmlsZSA+IC5saW5rIHtcbiAgdGV4dC1hbGlnbjogY2VudGVyO1xuICBwYWRkaW5nOiAzMHB4IDA7XG4gIGJvcmRlci10b3A6IDFweCBzb2xpZCAjZjFmM2Y2O1xuICBiYWNrZ3JvdW5kLWNvbG9yOiB3aGl0ZTtcbiAgdHJhbnNpdGlvbjogYmFja2dyb3VuZC1jb2xvciAwLjJzO1xufVxuLm1lbnUgPiAud3JhcHBlciA+IC5tZW51LW1vYmlsZSA+IC5saW5rcy1tb2JpbGUgPiAubGluazpob3ZlciB7XG4gIGJhY2tncm91bmQtY29sb3I6ICMwMDAwMDAwNTtcbn1cblxuLmhvbWUgPiAuc3RhcnQge1xuICBkaXNwbGF5OiBmbGV4O1xuICBmbGV4LWZsb3c6IGNvbHVtbjtcbn1cbkBtZWRpYSAobWluLXdpZHRoOiAxMjAwcHgpIHtcbiAgLmhvbWUgPiAuc3RhcnQge1xuICAgIGZsZXgtZmxvdzogcm93O1xuICB9XG59XG4uaG9tZSA+IC5zdGFydCA+IC5tYWluIHtcbiAgcGFkZGluZzogNXB4IDEwcHg7XG59XG5AbWVkaWEgKG1pbi13aWR0aDogNTc2cHgpIHtcbiAgLmhvbWUgPiAuc3RhcnQgPiAubWFpbiB7XG4gICAgcGFkZGluZzogMjBweDtcbiAgfVxufVxuQG1lZGlhIChtaW4td2lkdGg6IDEyMDBweCkge1xuICAuaG9tZSA+IC5zdGFydCA+IC5tYWluIHtcbiAgICBmbGV4OiAxO1xuICB9XG59XG4uaG9tZSA+IC5zdGFydCA+IC5tYWluID4gLnRpdGxlLXN1YnRpdGxlID4gLnRpdGxlIHtcbiAgZm9udC1zaXplOiAzMHB4O1xuICBsaW5lLWhlaWdodDogMzBweDtcbiAgbWFyZ2luLWJvdHRvbTogMTBweDtcbiAgZm9udC13ZWlnaHQ6IDgwMDtcbn1cbkBtZWRpYSAobWluLXdpZHRoOiA3NjhweCkge1xuICAuaG9tZSA+IC5zdGFydCA+IC5tYWluID4gLnRpdGxlLXN1YnRpdGxlID4gLnRpdGxlIHtcbiAgICBmb250LXNpemU6IDM1cHg7XG4gICAgbGluZS1oZWlnaHQ6IDM1cHg7XG4gICAgbWFyZ2luLWJvdHRvbTogMTVweDtcbiAgfVxufVxuQG1lZGlhIChtaW4td2lkdGg6IDEyMDBweCkge1xuICAuaG9tZSA+IC5zdGFydCA+IC5tYWluID4gLnRpdGxlLXN1YnRpdGxlID4gLnRpdGxlIHtcbiAgICBmb250LXNpemU6IDQycHg7XG4gICAgbGluZS1oZWlnaHQ6IDQwcHg7XG4gICAgbWFyZ2luLWJvdHRvbTogMjVweDtcbiAgfVxufVxuLmhvbWUgPiAuc3RhcnQgPiAubWFpbiA+IC50aXRsZS1zdWJ0aXRsZSA+IC5zdWJ0aXRsZSB7XG4gIGZvbnQtc2l6ZTogMTVweDtcbiAgY29sb3I6ICM4QThBOTA7XG59XG5AbWVkaWEgKG1pbi13aWR0aDogNzY4cHgpIHtcbiAgLmhvbWUgPiAuc3RhcnQgPiAubWFpbiA+IC50aXRsZS1zdWJ0aXRsZSA+IC5zdWJ0aXRsZSB7XG4gICAgZm9udC1zaXplOiAxOHB4O1xuICB9XG59XG5AbWVkaWEgKG1pbi13aWR0aDogMTIwMHB4KSB7XG4gIC5ob21lID4gLnN0YXJ0ID4gLm1haW4gPiAudGl0bGUtc3VidGl0bGUgPiAuc3VidGl0bGUge1xuICAgIGZvbnQtc2l6ZTogMjFweDtcbiAgfVxufVxuLmhvbWUgPiAuc3RhcnQgPiAubWFpbiA+IC5zbWFsbC1jYXJkcyB7XG4gIGRpc3BsYXk6IGdyaWQ7XG4gIGdyaWQtdGVtcGxhdGUtY29sdW1uczogMWZyO1xuICBncmlkLXRlbXBsYXRlLXJvd3M6IDFmciAxZnIgMWZyO1xuICBqdXN0aWZ5LWl0ZW1zOiBzdHJldGNoO1xuICBhbGlnbi1pdGVtczogc3RyZXRjaDtcbiAgbWFyZ2luOiAxNXB4IDA7XG4gIGdyaWQtY29sdW1uLWdhcDogMTBweDtcbiAgZ3JpZC1yb3ctZ2FwOiAyMHB4O1xufVxuQG1lZGlhIChtaW4td2lkdGg6IDU3NnB4KSB7XG4gIC5ob21lID4gLnN0YXJ0ID4gLm1haW4gPiAuc21hbGwtY2FyZHMge1xuICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogMWZyIDFmcjtcbiAgfVxufVxuQG1lZGlhIChtaW4td2lkdGg6IDEyMDBweCkge1xuICAuaG9tZSA+IC5zdGFydCA+IC5tYWluID4gLnNtYWxsLWNhcmRzIHtcbiAgICBncmlkLWNvbHVtbi1nYXA6IDQwcHg7XG4gICAgZ3JpZC1yb3ctZ2FwOiA0MHB4O1xuICAgIG1hcmdpbjogNTBweCAwO1xuICB9XG59XG4uaG9tZSA+IC5zdGFydCA+IC5tYWluID4gLnNtYWxsLWNhcmRzID4gLmNhcmQge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xuICBwYWRkaW5nOiA1cHg7XG59XG4uaG9tZSA+IC5zdGFydCA+IC5tYWluID4gLnNtYWxsLWNhcmRzID4gLmNhcmQgPiAudGh1bWJuYWlsIHtcbiAgd2lkdGg6IDE1NXB4O1xuICBtYXJnaW4tcmlnaHQ6IDI1cHg7XG59XG4uaG9tZSA+IC5zdGFydCA+IC5tYWluID4gLnNtYWxsLWNhcmRzID4gLmNhcmQgPiAudGh1bWJuYWlsID4gLmltYWdlIHtcbiAgd2lkdGg6IDEwMCU7XG59XG4uaG9tZSA+IC5zdGFydCA+IC5tYWluID4gLnNtYWxsLWNhcmRzID4gLmNhcmQgPiAuaW5mbyB7XG4gIHdpZHRoOiAxMDAlO1xufVxuLmhvbWUgPiAuc3RhcnQgPiAubWFpbiA+IC5zbWFsbC1jYXJkcyA+IC5jYXJkID4gLmluZm8gPiAudGl0bGUge1xuICBmb250LXdlaWdodDogODAwO1xuICBmb250LXNpemU6IDIxcHg7XG4gIG1hcmdpbi1ib3R0b206IDVweDtcbn1cbi5ob21lID4gLnN0YXJ0ID4gLm1haW4gPiAuc21hbGwtY2FyZHMgPiAuY2FyZCA+IC5pbmZvID4gLmRlc2NyaXB0aW9uIHtcbiAgZm9udC13ZWlnaHQ6IDUwMDtcbiAgZm9udC1zaXplOiAxM3B4O1xuICBtYXJnaW4tdG9wOiA1cHg7XG4gIGxpbmUtaGVpZ2h0OiAyMHB4O1xufVxuLmhvbWUgPiAuc3RhcnQgPiAubWFpbiA+IC5zbWFsbC1jYXJkcyA+IC5jYXJkID4gLmluZm8gPiAubGluayB7XG4gIHdpZHRoOiBjYWxjKDEwMCUgLSA0MHB4KTtcbiAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICB0ZXh0LWFsaWduOiByaWdodDtcbiAgbWFyZ2luLXRvcDogMjVweDtcbiAgZm9udC1zaXplOiAxMXB4O1xuICBjb2xvcjogIzAwMjhmZjtcbn1cbi5ob21lID4gLnN0YXJ0ID4gLmFzaWRlIHtcbiAgcGFkZGluZzogMTVweDtcbn1cbkBtZWRpYSAobWluLXdpZHRoOiAxMjAwcHgpIHtcbiAgLmhvbWUgPiAuc3RhcnQgPiAuYXNpZGUge1xuICAgIHBhZGRpbmc6IDIwcHg7XG4gICAgd2lkdGg6IDQ3MHB4O1xuICB9XG59XG4uaG9tZSA+IC5zdGFydCA+IC5hc2lkZSA+IC5hc2lkZS1jYXJkcyB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZmxvdzogY29sdW1uO1xufVxuLmhvbWUgPiAuc3RhcnQgPiAuYXNpZGUgPiAuYXNpZGUtY2FyZHMgPiAuY2FyZCB7XG4gIGhlaWdodDogMzAwcHg7XG4gIGJhY2tncm91bmQ6ICNkYWRhZGE7XG4gIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgb3ZlcmZsb3c6IGhpZGRlbjtcbiAgY3Vyc29yOiBwb2ludGVyO1xufVxuQG1lZGlhIChtaW4td2lkdGg6IDEyMDBweCkge1xuICAuaG9tZSA+IC5zdGFydCA+IC5hc2lkZSA+IC5hc2lkZS1jYXJkcyA+IC5jYXJkIHtcbiAgICBoZWlnaHQ6IDQxMHB4O1xuICB9XG59XG4uaG9tZSA+IC5zdGFydCA+IC5hc2lkZSA+IC5hc2lkZS1jYXJkcyA+IC5jYXJkOmhvdmVyID4gLmJhY2tncm91bmQtaW1nIHtcbiAgdHJhbnNmb3JtOiBzY2FsZSgxLjEpIHRyYW5zbGF0ZVkoLTQ1JSk7XG59XG4uaG9tZSA+IC5zdGFydCA+IC5hc2lkZSA+IC5hc2lkZS1jYXJkcyA+IC5jYXJkID4gLmJhY2tncm91bmQtaW1nIHtcbiAgdG9wOiA1MCU7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgtNTAlKTtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICB3aWR0aDogMTAwJTtcbiAgbWluLWhlaWdodDogMTAwJTtcbiAgei1pbmRleDogMTtcbiAgdHJhbnNpdGlvbjogdHJhbnNmb3JtIDAuMnM7XG59XG4uaG9tZSA+IC5zdGFydCA+IC5hc2lkZSA+IC5hc2lkZS1jYXJkcyA+IC5jYXJkID4gLnJlYWQtbW9yZSB7XG4gIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgei1pbmRleDogMztcbiAgYm90dG9tOiAwO1xuICByaWdodDogMDtcbiAgY29sb3I6IHdoaXRlO1xuICBmb250LXNpemU6IDExcHg7XG4gIHBhZGRpbmc6IDEwcHggMjBweDtcbn1cbkBtZWRpYSAobWluLXdpZHRoOiAxMjAwcHgpIHtcbiAgLmhvbWUgPiAuc3RhcnQgPiAuYXNpZGUgPiAuYXNpZGUtY2FyZHMgPiAuY2FyZCA+IC5yZWFkLW1vcmUge1xuICAgIGZvbnQtc2l6ZTogaW5oZXJpdDtcbiAgfVxufVxuLmhvbWUgPiAuc3RhcnQgPiAuYXNpZGUgPiAuYXNpZGUtY2FyZHMgPiAuY2FyZCA+IC50aXRsZS1kZXNjcmlwdGlvbiB7XG4gIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgei1pbmRleDogMjtcbiAgY29sb3I6IHdoaXRlO1xuICB3aWR0aDogMTAwJTtcbiAgYm90dG9tOiAwO1xuICBwYWRkaW5nOiAyMHB4IDE1cHggMzBweCAxNXB4O1xuICBiYWNrZ3JvdW5kOiAjMDAwMDAwYjg7XG59XG5AbWVkaWEgKG1pbi13aWR0aDogMTIwMHB4KSB7XG4gIC5ob21lID4gLnN0YXJ0ID4gLmFzaWRlID4gLmFzaWRlLWNhcmRzID4gLmNhcmQgPiAudGl0bGUtZGVzY3JpcHRpb24ge1xuICAgIHBhZGRpbmc6IDMwcHggMjBweCA0MHB4IDIwcHg7XG4gIH1cbn1cbi5ob21lID4gLnN0YXJ0ID4gLmFzaWRlID4gLmFzaWRlLWNhcmRzID4gLmNhcmQgPiAudGl0bGUtZGVzY3JpcHRpb24gPiAudGl0bGUge1xuICBmb250LXNpemU6IDI3cHg7XG4gIGZvbnQtd2VpZ2h0OiA4MDA7XG4gIG1hcmdpbi1ib3R0b206IDVweDtcbn1cbkBtZWRpYSAobWluLXdpZHRoOiAxMjAwcHgpIHtcbiAgLmhvbWUgPiAuc3RhcnQgPiAuYXNpZGUgPiAuYXNpZGUtY2FyZHMgPiAuY2FyZCA+IC50aXRsZS1kZXNjcmlwdGlvbiA+IC50aXRsZSB7XG4gICAgbWFyZ2luLWJvdHRvbTogMTVweDtcbiAgICBmb250LXNpemU6IDM0cHg7XG4gIH1cbn1cbi5ob21lID4gLnN0YXJ0ID4gLmFzaWRlID4gLmFzaWRlLWNhcmRzID4gLmNhcmQgPiAudGl0bGUtZGVzY3JpcHRpb24gPiAuZGVzY3JpcHRpb24ge1xuICBmb250LXNpemU6IDE1cHg7XG4gIGxpbmUtaGVpZ2h0OiAyMHB4O1xufVxuQG1lZGlhIChtaW4td2lkdGg6IDEyMDBweCkge1xuICAuaG9tZSA+IC5zdGFydCA+IC5hc2lkZSA+IC5hc2lkZS1jYXJkcyA+IC5jYXJkID4gLnRpdGxlLWRlc2NyaXB0aW9uID4gLmRlc2NyaXB0aW9uIHtcbiAgICBmb250LXNpemU6IDEzcHg7XG4gICAgbGluZS1oZWlnaHQ6IDMwcHg7XG4gIH1cbn1cblxuLmJ0biB7XG4gIGJhY2tncm91bmQ6ICMwMDI4ZmY7XG4gIGNvbG9yOiB3aGl0ZTtcbiAgZm9udC1zaXplOiAyNHB4O1xuICB0ZXh0LWFsaWduOiBsZWZ0O1xuICBtYXgtd2lkdGg6IDMwMHB4O1xuICBmb250LXdlaWdodDogODAwO1xuICBib3JkZXI6IG5vbmU7XG4gIGJvcmRlci1yYWRpdXM6IDNweDtcbiAgcGFkZGluZzogMTVweCAzMHB4O1xuICB0cmFuc2l0aW9uOiAwLjJzO1xuICBjdXJzb3I6IHBvaW50ZXI7XG59XG4uYnRuOmhvdmVyIHtcbiAgYmFja2dyb3VuZDogIzAwMjRlNjtcbn1cblxuLmd1aWRlLWRldGFpbCB7XG4gIHBhZGRpbmc6IDEwcHggMTVweDtcbn1cbkBtZWRpYSAobWluLXdpZHRoOiAxMjAwcHgpIHtcbiAgLmd1aWRlLWRldGFpbCB7XG4gICAgcGFkZGluZzogNTBweCAxNSU7XG4gIH1cbn1cbi5ndWlkZS1kZXRhaWwgPiAuaGVhZGVyID4gLnRpdGxlIHtcbiAgZm9udC1zaXplOiAzMHB4O1xuICBsaW5lLWhlaWdodDogMzBweDtcbiAgbWFyZ2luLWJvdHRvbTogMTBweDtcbiAgZm9udC13ZWlnaHQ6IDgwMDtcbn1cbkBtZWRpYSAobWluLXdpZHRoOiA3NjhweCkge1xuICAuZ3VpZGUtZGV0YWlsID4gLmhlYWRlciA+IC50aXRsZSB7XG4gICAgZm9udC1zaXplOiAzNXB4O1xuICAgIGxpbmUtaGVpZ2h0OiAzNXB4O1xuICAgIG1hcmdpbi1ib3R0b206IDE1cHg7XG4gIH1cbn1cbkBtZWRpYSAobWluLXdpZHRoOiAxMjAwcHgpIHtcbiAgLmd1aWRlLWRldGFpbCA+IC5oZWFkZXIgPiAudGl0bGUge1xuICAgIGZvbnQtc2l6ZTogNDJweDtcbiAgICBsaW5lLWhlaWdodDogNDBweDtcbiAgICBtYXJnaW4tYm90dG9tOiAyNXB4O1xuICB9XG59XG4uZ3VpZGUtZGV0YWlsID4gLmhlYWRlciA+IC5zdWJ0aXRsZSB7XG4gIGZvbnQtc2l6ZTogMTVweDtcbiAgY29sb3I6ICM4QThBOTA7XG4gIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7XG4gIG1hcmdpbi1ib3R0b206IDVweDtcbn1cbkBtZWRpYSAobWluLXdpZHRoOiA3NjhweCkge1xuICAuZ3VpZGUtZGV0YWlsID4gLmhlYWRlciA+IC5zdWJ0aXRsZSB7XG4gICAgZm9udC1zaXplOiAxOHB4O1xuICAgIG1hcmdpbi1ib3R0b206IDEwcHg7XG4gIH1cbn1cbkBtZWRpYSAobWluLXdpZHRoOiAxMjAwcHgpIHtcbiAgLmd1aWRlLWRldGFpbCA+IC5oZWFkZXIgPiAuc3VidGl0bGUge1xuICAgIGZvbnQtc2l6ZTogMjFweDtcbiAgICBtYXJnaW4tYm90dG9tOiAyMHB4O1xuICB9XG59XG4uZ3VpZGUtZGV0YWlsID4gLmhlYWRlciA+IC50aW1lIHtcbiAgZm9udC1zaXplOiAxM3B4O1xuICBjb2xvcjogIzhBOEE5MDtcbn1cbkBtZWRpYSAobWluLXdpZHRoOiA3NjhweCkge1xuICAuZ3VpZGUtZGV0YWlsID4gLmhlYWRlciA+IC50aW1lIHtcbiAgICBmb250LXNpemU6IDE1cHg7XG4gIH1cbn1cbkBtZWRpYSAobWluLXdpZHRoOiAxMjAwcHgpIHtcbiAgLmd1aWRlLWRldGFpbCA+IC5oZWFkZXIgPiAudGltZSB7XG4gICAgZm9udC1zaXplOiAxOHB4O1xuICB9XG59XG4uZ3VpZGUtZGV0YWlsID4gLnVwcGVyLXRodW1iIHtcbiAgZGlzcGxheTogZmxleDtcbiAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xuICBtYXJnaW46IDMwcHggMCAzMHB4IDA7XG59XG4uZ3VpZGUtZGV0YWlsID4gLnVwcGVyLXRodW1iID4gLmxpc3RlbiB7XG4gIGZvbnQtc2l6ZTogMjBweDtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgY29sb3I6ICMwMDI0ZTY7XG4gIHRyYW5zaXRpb246IGNvbG9yIDAuMnM7XG4gIGN1cnNvcjogcG9pbnRlcjtcbn1cbi5ndWlkZS1kZXRhaWwgPiAudXBwZXItdGh1bWIgPiAubGlzdGVuOmhvdmVyIHtcbiAgY29sb3I6ICMwMDE4OTk7XG59XG4uZ3VpZGUtZGV0YWlsID4gLnVwcGVyLXRodW1iID4gLmxpc3RlbiA+IC50ZXh0IHtcbiAgZm9udC13ZWlnaHQ6IDYwMDtcbiAgbWFyZ2luLXJpZ2h0OiAxMHB4O1xufVxuLmd1aWRlLWRldGFpbCA+IC51cHBlci10aHVtYiA+IC5saXN0ZW4gPiAucGxheSB7XG4gIGZvbnQtc2l6ZTogMjhweDtcbn1cbi5ndWlkZS1kZXRhaWwgPiAudXBwZXItdGh1bWIgPiAuc2hhcmUge1xuICBmb250LXNpemU6IDI4cHg7XG59XG4uZ3VpZGUtZGV0YWlsID4gLnVwcGVyLXRodW1iID4gLnNoYXJlID4gLmljb24ge1xuICBtYXJnaW4tbGVmdDogMTBweDtcbiAgdHJhbnNpdGlvbjogY29sb3IgMC4ycztcbn1cbi5ndWlkZS1kZXRhaWwgPiAudXBwZXItdGh1bWIgPiAuc2hhcmUgPiAuaWNvbjpob3ZlciB7XG4gIGNvbG9yOiAjMDAyOGZmO1xufVxuLmd1aWRlLWRldGFpbCA+IC50aHVtYiB7XG4gIG1hcmdpbi10b3A6IDIwcHg7XG4gIG1hcmdpbi1ib3R0b206IDIwcHg7XG59XG4uZ3VpZGUtZGV0YWlsID4gLnRodW1iID4gLmltZy13cmFwcGVyIHtcbiAgcG9zaXRpb246IHJlbGF0aXZlO1xuICBoZWlnaHQ6IDI1MHB4O1xuICBvdmVyZmxvdzogaGlkZGVuO1xufVxuLmd1aWRlLWRldGFpbCA+IC50aHVtYiA+IC5pbWctd3JhcHBlciA+IC5pbWcge1xuICB0b3A6IDUwJTtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC01MCUpO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHdpZHRoOiAxMDAlO1xuICBtaW4taGVpZ2h0OiAxMDAlO1xufVxuLmd1aWRlLWRldGFpbCA+IC50aHVtYiA+IC5kZXNjcmlwdGlvbiB7XG4gIG1hcmdpbi10b3A6IDdweDtcbiAgZm9udC1zaXplOiAxM3B4O1xuICBjb2xvcjogIzhBOEE5MDtcbn1cbi5ndWlkZS1kZXRhaWwgLnNtYWxsLXRpdGxlIHtcbiAgZm9udC1zaXplOiAyMnB4O1xuICBmb250LXdlaWdodDogODAwO1xuICBtYXJnaW4tYm90dG9tOiAyNXB4O1xuICBtYXJnaW4tdG9wOiA1MHB4O1xufVxuLmd1aWRlLWRldGFpbCA+IC5yZWZlcmVuY2VzIC5saW5rIHtcbiAgY29sb3I6ICMwMDI4ZmY7XG4gIGRpc3BsYXk6IGlubGluZS1ibG9jaztcbiAgbWFyZ2luLWJvdHRvbTogMTVweDtcbiAgY3Vyc29yOiBwb2ludGVyO1xuICBmb250LXNpemU6IDEycHg7XG59XG4uZ3VpZGUtZGV0YWlsID4gLmd1aWRlID4gLnBhcmFncmFwaCB7XG4gIGxpbmUtaGVpZ2h0OiAyNnB4O1xuICBtYXJnaW4tYm90dG9tOiAyMHB4O1xufVxuLmd1aWRlLWRldGFpbCA+IC5ndWlkZSA+IC5wYXJhZ3JhcGguLWlzLXN0ZXAge1xuICBtYXJnaW4tYm90dG9tOiAwO1xufVxuLmd1aWRlLWRldGFpbCA+IC5ndWlkZSA+IC5wYXJhZ3JhcGguLWlzLWxhc3Qtc3RlcCB7XG4gIG1hcmdpbi1ib3R0b206IDIwcHg7XG59XG4uZ3VpZGUtZGV0YWlsID4gLmd1aWRlID4gLnBhcmFncmFwaCA+IC5zdGVwIHtcbiAgZm9udC13ZWlnaHQ6IDgwMDtcbiAgY29sb3I6ICMwMDI4ZmY7XG4gIGZvbnQtc2l6ZTogMjBweDtcbiAgbWFyZ2luLXJpZ2h0OiA1cHg7XG59XG4uZ3VpZGUtZGV0YWlsID4gLnNoYXJlLW5leHQge1xuICBkaXNwbGF5OiBmbGV4O1xuICBqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47XG4gIGFsaWduLWl0ZW1zOiBmbGV4LXN0YXJ0O1xuICBtYXJnaW4tdG9wOiAzMHB4O1xufVxuLmd1aWRlLWRldGFpbCA+IC5zaGFyZS1uZXh0ID4gLnNoYXJlID4gLnNtYWxsLXRpdGxlIHtcbiAgbWFyZ2luLXRvcDogMDtcbn1cblxuLl90ZXh0LWNlbnRlciB7XG4gIHRleHQtYWxpZ246IGNlbnRlcjtcbn0iLCJodG1sLFxyXG5ib2R5IHtcclxuICBmb250LWZhbWlseTogJ01vbnRzZXJyYXQnLCBzYW5zLXNlcmlmO1xyXG4gIGZvbnQtd2VpZ2h0OiA1MDA7XHJcbiAgY29sb3I6ICRjb2xvci1zZWNvbmRhcnk7XHJcbiAgbWluLWhlaWdodDogMTAwdmg7XHJcbiAgb3ZlcmZsb3c6IGF1dG87XHJcbn1cclxuXHJcbioge1xyXG4gIGJveC1zaXppbmc6IGJvcmRlci1ib3g7XHJcbiAgb3V0bGluZTogbm9uZTtcclxufVxyXG5cclxuYm9keSB7XHJcbiAgb3ZlcmZsb3c6IGhpZGRlbjtcclxufVxyXG5cclxuYSB7XHJcbiAgdGV4dC1kZWNvcmF0aW9uOiBub25lO1xyXG4gIGNvbG9yOiBpbmhlcml0O1xyXG59XHJcblxyXG4uYXBwLWNvbnRlbnQge1xyXG4gIHBhZGRpbmc6IDE1cHggMDtcclxuXHJcbiAgQG1lZGlhIChtaW4td2lkdGg6ICRsYXJnZS1tb2JpbGUpIHtcclxuICAgIHBhZGRpbmc6IDIwcHggMDtcclxuICB9XHJcbn1cclxuXHJcbjo6LXdlYmtpdC1zY3JvbGxiYXIge1xyXG4gIHdpZHRoOiA3cHhcclxufVxyXG5cclxuOjotd2Via2l0LXNjcm9sbGJhci10cmFjayB7XHJcbiAgYmFja2dyb3VuZDogI2RkZGRkZDtcclxuICBib3JkZXItcmFkaXVzOiAxMHB4XHJcbn1cclxuXHJcbjo6LXdlYmtpdC1zY3JvbGxiYXItdGh1bWIge1xyXG4gIGJhY2tncm91bmQ6ICMyNDI0MjQ7XHJcbiAgYm9yZGVyLXJhZGl1czogMTBweFxyXG59XHJcblxyXG4uY29udGFpbmVyIHtcclxuICB3aWR0aDogMTAwJTtcclxuICBtYXJnaW46IDAgYXV0bztcclxuXHJcbiAgQG1lZGlhIChtaW4td2lkdGg6ICR0YWJsZXQpIHtcclxuICAgIHBhZGRpbmc6IDAgMTBweDtcclxuICAgIG1heC13aWR0aDogY2FsYygjeyR0YWJsZXR9ICsgMTAwcHgpO1xyXG4gIH1cclxuXHJcbiAgQG1lZGlhIChtaW4td2lkdGg6ICRsYXB0b3ApIHtcclxuICAgIG1heC13aWR0aDogY2FsYygjeyRsYXB0b3B9ICsgMTAwcHgpO1xyXG4gIH1cclxuXHJcbiAgQG1lZGlhIChtaW4td2lkdGg6ICRkZXNrdG9wKSB7XHJcbiAgICBtYXgtd2lkdGg6IGNhbGMoI3skZGVza3RvcH0gKyAxMDBweCk7XHJcbiAgfVxyXG5cclxuICBAbWVkaWEgKG1pbi13aWR0aDogJGxhcmdlLWRlc2t0b3ApIHtcclxuICAgIG1heC13aWR0aDogY2FsYygjeyRsYXJnZS1kZXNrdG9wfSArIDEwMHB4KTtcclxuICB9XHJcbn0iLCIkbGFyZ2UtbW9iaWxlOiA1NzZweDtcclxuJHRhYmxldDogNzY4cHg7XHJcbiRsYXB0b3A6IDk5MnB4O1xyXG4kZGVza3RvcDogMTIwMHB4O1xyXG4kbGFyZ2UtZGVza3RvcDogMTQ0MHB4O1xyXG5cclxuJGNvbG9yLXByaW1hcnk6ICMwMDI4ZmY7XHJcbiRjb2xvci1zZWNvbmRhcnk6ICMxNTE1MjI7XHJcbiRjb2xvci1ncmF5OiAjOEE4QTkwO1xyXG4kY29sb3ItbGlnaHQtZ3JheTogI2YxZjNmNjsiLCIuZm9vdGVyIHtcclxuICBiYWNrZ3JvdW5kOiAkY29sb3Itc2Vjb25kYXJ5O1xyXG4gIGNvbG9yOiB3aGl0ZTtcclxuXHJcbiAgPi53cmFwcGVyIHtcclxuICAgIHBhZGRpbmc6IDUwcHggMjVweDtcclxuICAgIGRpc3BsYXk6IGdyaWQ7XHJcbiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDFmciAxZnIgMS43ZnI7XHJcbiAgICBncmlkLWdhcDogNzBweDtcclxuXHJcbiAgICA+LnNlY3Rpb24ge1xyXG5cclxuICAgICAgPi50aXRsZSB7XHJcbiAgICAgICAgZm9udC13ZWlnaHQ6IDgwMDtcclxuICAgICAgICBtYXJnaW4tYm90dG9tOiAyNXB4O1xyXG5cclxuICAgICAgfVxyXG5cclxuICAgICAgPnVsPmxpIHtcclxuICAgICAgICBtYXJnaW4tYm90dG9tOiAyMHB4O1xyXG4gICAgICAgIGRpc3BsYXk6IGZsZXg7XHJcbiAgICAgICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xyXG4gICAgICB9XHJcbiAgICB9XHJcbiAgfVxyXG59IiwiLm1lbnUge1xyXG4gIGhlaWdodDogODBweDtcclxuICBtYXJnaW4tYm90dG9tOiAwO1xyXG4gIGJveC1zaGFkb3c6IDBweCA0cHggMTRweCAjMDAwMDAwMWM7XHJcblxyXG4gIEBtZWRpYShtaW4td2lkdGg6ICR0YWJsZXQpIHtcclxuICAgIG1hcmdpbi1ib3R0b206IDE1cHg7XHJcbiAgfVxyXG5cclxuICBAbWVkaWEobWluLXdpZHRoOiAkZGVza3RvcCkge1xyXG4gICAgbWFyZ2luLWJvdHRvbTogMzVweDtcclxuICB9XHJcblxyXG4gID4ud3JhcHBlciB7XHJcbiAgICBkaXNwbGF5OiBmbGV4O1xyXG4gICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xyXG4gICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcclxuICAgIGhlaWdodDogMTAwJTtcclxuICAgIHBvc2l0aW9uOiByZWxhdGl2ZTtcclxuXHJcbiAgICA+LmxvZ28ge1xyXG4gICAgICB3aWR0aDogMTIwcHg7XHJcbiAgICAgIG1hcmdpbi1sZWZ0OiAyMHB4O1xyXG5cclxuICAgICAgPi5pbWFnZSB7XHJcbiAgICAgICAgd2lkdGg6IDEwMCU7XHJcbiAgICAgIH1cclxuICAgIH1cclxuXHJcbiAgICA+LmxpbmtzLWRlc2t0b3Age1xyXG4gICAgICBkaXNwbGF5OiBub25lO1xyXG5cclxuICAgICAgQG1lZGlhKG1pbi13aWR0aDogJGxhcmdlLW1vYmlsZSkge1xyXG4gICAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jaztcclxuICAgICAgfVxyXG5cclxuICAgICAgPi5saW5rIHtcclxuICAgICAgICBwYWRkaW5nOiAyMHB4IDI1cHg7XHJcblxyXG4gICAgICAgICYuLWFjdGl2ZSB7XHJcbiAgICAgICAgICBjb2xvcjogJGNvbG9yLXByaW1hcnk7XHJcbiAgICAgICAgICBmb250LXdlaWdodDogODAwO1xyXG4gICAgICAgIH1cclxuICAgICAgfVxyXG4gICAgfVxyXG5cclxuICAgID4ubWVudS1tb2JpbGUge1xyXG4gICAgICBjdXJzb3I6IHBvaW50ZXI7XHJcblxyXG4gICAgICBAbWVkaWEobWluLXdpZHRoOiAkbGFyZ2UtbW9iaWxlKSB7XHJcbiAgICAgICAgZGlzcGxheTogbm9uZTtcclxuICAgICAgfVxyXG5cclxuICAgICAgJi4tYWN0aXZlIHtcclxuICAgICAgICA+LmxpbmtzLW1vYmlsZSB7XHJcbiAgICAgICAgICB0b3A6IDcwcHg7XHJcbiAgICAgICAgICBvcGFjaXR5OiAxO1xyXG4gICAgICAgIH1cclxuICAgICAgfVxyXG5cclxuICAgICAgPi5saW5rcy1tb2JpbGUge1xyXG4gICAgICAgIGRpc3BsYXk6IGZsZXg7XHJcbiAgICAgICAgZmxleC1mbG93OiBjb2x1bW47XHJcbiAgICAgICAgcG9zaXRpb246IGFic29sdXRlO1xyXG4gICAgICAgIGxlZnQ6IDA7XHJcbiAgICAgICAgdHJhbnNpdGlvbjogMXM7XHJcbiAgICAgICAgdG9wOiAtMjUwcHg7XHJcbiAgICAgICAgb3BhY2l0eTogMDtcclxuICAgICAgICB3aWR0aDogMTAwJTtcclxuICAgICAgICBiYWNrZ3JvdW5kOiB3aGl0ZTtcclxuICAgICAgICBib3gtc2hhZG93OiAwcHggNnB4IDE3cHggIzAwMDAwMDEyO1xyXG5cclxuICAgICAgICA+Lmxpbmsge1xyXG4gICAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xyXG4gICAgICAgICAgcGFkZGluZzogMzBweCAwO1xyXG4gICAgICAgICAgYm9yZGVyLXRvcDogMXB4IHNvbGlkICRjb2xvci1saWdodC1ncmF5O1xyXG4gICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogd2hpdGU7XHJcbiAgICAgICAgICB0cmFuc2l0aW9uOiBiYWNrZ3JvdW5kLWNvbG9yIC4ycztcclxuXHJcbiAgICAgICAgICAmOmhvdmVyIHtcclxuICAgICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogIzAwMDAwMDA1O1xyXG4gICAgICAgICAgfVxyXG4gICAgICAgIH1cclxuICAgICAgfVxyXG4gICAgfVxyXG4gIH1cclxufSIsIi5ob21lIHtcclxuICA+LnN0YXJ0IHtcclxuICAgIGRpc3BsYXk6IGZsZXg7XHJcbiAgICBmbGV4LWZsb3c6IGNvbHVtbjtcclxuXHJcbiAgICBAbWVkaWEgKG1pbi13aWR0aDogJGRlc2t0b3ApIHtcclxuICAgICAgZmxleC1mbG93OiByb3c7XHJcbiAgICB9XHJcblxyXG4gICAgPi5tYWluIHtcclxuICAgICAgcGFkZGluZzogNXB4IDEwcHg7XHJcblxyXG4gICAgICBAbWVkaWEgKG1pbi13aWR0aDogJGxhcmdlLW1vYmlsZSkge1xyXG4gICAgICAgIHBhZGRpbmc6IDIwcHg7XHJcbiAgICAgIH1cclxuXHJcbiAgICAgIEBtZWRpYSAobWluLXdpZHRoOiAkZGVza3RvcCkge1xyXG4gICAgICAgIGZsZXg6IDE7XHJcbiAgICAgIH1cclxuXHJcbiAgICAgID4udGl0bGUtc3VidGl0bGUge1xyXG4gICAgICAgID4udGl0bGUge1xyXG4gICAgICAgICAgZm9udC1zaXplOiAzMHB4O1xyXG4gICAgICAgICAgbGluZS1oZWlnaHQ6IDMwcHg7XHJcbiAgICAgICAgICBtYXJnaW4tYm90dG9tOiAxMHB4O1xyXG4gICAgICAgICAgZm9udC13ZWlnaHQ6IDgwMDtcclxuXHJcbiAgICAgICAgICBAbWVkaWEobWluLXdpZHRoOiAkdGFibGV0KSB7XHJcbiAgICAgICAgICAgIGZvbnQtc2l6ZTogMzVweDtcclxuICAgICAgICAgICAgbGluZS1oZWlnaHQ6IDM1cHg7XHJcbiAgICAgICAgICAgIG1hcmdpbi1ib3R0b206IDE1cHg7XHJcbiAgICAgICAgICB9XHJcblxyXG4gICAgICAgICAgQG1lZGlhKG1pbi13aWR0aDogJGRlc2t0b3ApIHtcclxuICAgICAgICAgICAgZm9udC1zaXplOiA0MnB4O1xyXG4gICAgICAgICAgICBsaW5lLWhlaWdodDogNDBweDtcclxuICAgICAgICAgICAgbWFyZ2luLWJvdHRvbTogMjVweDtcclxuICAgICAgICAgIH1cclxuICAgICAgICB9XHJcblxyXG4gICAgICAgID4uc3VidGl0bGUge1xyXG4gICAgICAgICAgZm9udC1zaXplOiAxNXB4O1xyXG4gICAgICAgICAgY29sb3I6ICRjb2xvci1ncmF5O1xyXG5cclxuICAgICAgICAgIEBtZWRpYShtaW4td2lkdGg6ICR0YWJsZXQpIHtcclxuICAgICAgICAgICAgZm9udC1zaXplOiAxOHB4O1xyXG4gICAgICAgICAgfVxyXG5cclxuICAgICAgICAgIEBtZWRpYShtaW4td2lkdGg6ICRkZXNrdG9wKSB7XHJcbiAgICAgICAgICAgIGZvbnQtc2l6ZTogMjFweDtcclxuICAgICAgICAgIH1cclxuICAgICAgICB9XHJcbiAgICAgIH1cclxuXHJcbiAgICAgID4uc21hbGwtY2FyZHMge1xyXG4gICAgICAgIGRpc3BsYXk6IGdyaWQ7XHJcbiAgICAgICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiAxZnI7XHJcbiAgICAgICAgZ3JpZC10ZW1wbGF0ZS1yb3dzOiAxZnIgMWZyIDFmcjtcclxuICAgICAgICBqdXN0aWZ5LWl0ZW1zOiBzdHJldGNoO1xyXG4gICAgICAgIGFsaWduLWl0ZW1zOiBzdHJldGNoO1xyXG4gICAgICAgIG1hcmdpbjogMTVweCAwO1xyXG4gICAgICAgIGdyaWQtY29sdW1uLWdhcDogMTBweDtcclxuICAgICAgICBncmlkLXJvdy1nYXA6IDIwcHg7XHJcblxyXG5cclxuXHJcbiAgICAgICAgQG1lZGlhIChtaW4td2lkdGg6ICRsYXJnZS1tb2JpbGUpIHtcclxuICAgICAgICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogMWZyIDFmcjtcclxuICAgICAgICB9XHJcblxyXG4gICAgICAgIEBtZWRpYShtaW4td2lkdGg6ICRkZXNrdG9wKSB7XHJcbiAgICAgICAgICBncmlkLWNvbHVtbi1nYXA6IDQwcHg7XHJcbiAgICAgICAgICBncmlkLXJvdy1nYXA6IDQwcHg7XHJcbiAgICAgICAgICBtYXJnaW46IDUwcHggMDtcclxuICAgICAgICB9XHJcblxyXG4gICAgICAgID4uY2FyZCB7XHJcbiAgICAgICAgICBkaXNwbGF5OiBmbGV4O1xyXG4gICAgICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcclxuICAgICAgICAgIHBhZGRpbmc6IDVweDtcclxuXHJcbiAgICAgICAgICA+LnRodW1ibmFpbCB7XHJcbiAgICAgICAgICAgIHdpZHRoOiAxNTVweDtcclxuICAgICAgICAgICAgbWFyZ2luLXJpZ2h0OiAyNXB4O1xyXG5cclxuICAgICAgICAgICAgPi5pbWFnZSB7XHJcbiAgICAgICAgICAgICAgd2lkdGg6IDEwMCU7XHJcbiAgICAgICAgICAgIH1cclxuICAgICAgICAgIH1cclxuXHJcbiAgICAgICAgICA+LmluZm8ge1xyXG4gICAgICAgICAgICB3aWR0aDogMTAwJTtcclxuXHJcbiAgICAgICAgICAgID4udGl0bGUge1xyXG4gICAgICAgICAgICAgIGZvbnQtd2VpZ2h0OiA4MDA7XHJcbiAgICAgICAgICAgICAgZm9udC1zaXplOiAyMXB4O1xyXG4gICAgICAgICAgICAgIG1hcmdpbi1ib3R0b206IDVweDtcclxuICAgICAgICAgICAgfVxyXG5cclxuICAgICAgICAgICAgPi5kZXNjcmlwdGlvbiB7XHJcbiAgICAgICAgICAgICAgZm9udC13ZWlnaHQ6IDUwMDtcclxuICAgICAgICAgICAgICBmb250LXNpemU6IDEzcHg7XHJcbiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogNXB4O1xyXG4gICAgICAgICAgICAgIGxpbmUtaGVpZ2h0OiAyMHB4O1xyXG4gICAgICAgICAgICB9XHJcblxyXG4gICAgICAgICAgICA+Lmxpbmsge1xyXG4gICAgICAgICAgICAgIHdpZHRoOiBjYWxjKDEwMCUgLSA0MHB4KTtcclxuICAgICAgICAgICAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XHJcbiAgICAgICAgICAgICAgdGV4dC1hbGlnbjogcmlnaHQ7XHJcbiAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMjVweDtcclxuICAgICAgICAgICAgICBmb250LXNpemU6IDExcHg7XHJcbiAgICAgICAgICAgICAgY29sb3I6ICRjb2xvci1wcmltYXJ5O1xyXG4gICAgICAgICAgICB9XHJcbiAgICAgICAgICB9XHJcbiAgICAgICAgfVxyXG4gICAgICB9XHJcblxyXG4gICAgfVxyXG5cclxuICAgID4uYXNpZGUge1xyXG4gICAgICBwYWRkaW5nOiAxNXB4O1xyXG5cclxuICAgICAgQG1lZGlhIChtaW4td2lkdGg6ICRkZXNrdG9wKSB7XHJcbiAgICAgICAgcGFkZGluZzogMjBweDtcclxuICAgICAgICB3aWR0aDogNDcwcHg7XHJcbiAgICAgIH1cclxuXHJcbiAgICAgID4uYXNpZGUtY2FyZHMge1xyXG5cclxuICAgICAgICBkaXNwbGF5OiBmbGV4O1xyXG4gICAgICAgIGZsZXgtZmxvdzogY29sdW1uO1xyXG5cclxuICAgICAgICA+LmNhcmQge1xyXG4gICAgICAgICAgaGVpZ2h0OiAzMDBweDtcclxuICAgICAgICAgIGJhY2tncm91bmQ6ICNkYWRhZGE7XHJcbiAgICAgICAgICBwb3NpdGlvbjogcmVsYXRpdmU7XHJcbiAgICAgICAgICBvdmVyZmxvdzogaGlkZGVuO1xyXG4gICAgICAgICAgY3Vyc29yOiBwb2ludGVyO1xyXG5cclxuICAgICAgICAgIEBtZWRpYSAobWluLXdpZHRoOiAkZGVza3RvcCkge1xyXG4gICAgICAgICAgICBoZWlnaHQ6IDQxMHB4O1xyXG4gICAgICAgICAgfVxyXG5cclxuICAgICAgICAgICY6aG92ZXIge1xyXG4gICAgICAgICAgICA+LmJhY2tncm91bmQtaW1nIHtcclxuICAgICAgICAgICAgICB0cmFuc2Zvcm06IHNjYWxlKDEuMSkgdHJhbnNsYXRlWSgtNDUlKTtcclxuICAgICAgICAgICAgfVxyXG4gICAgICAgICAgfVxyXG5cclxuICAgICAgICAgID4uYmFja2dyb3VuZC1pbWcge1xyXG4gICAgICAgICAgICB0b3A6IDUwJTtcclxuICAgICAgICAgICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC01MCUpO1xyXG4gICAgICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XHJcbiAgICAgICAgICAgIHdpZHRoOiAxMDAlO1xyXG4gICAgICAgICAgICBtaW4taGVpZ2h0OiAxMDAlO1xyXG4gICAgICAgICAgICB6LWluZGV4OiAxO1xyXG4gICAgICAgICAgICB0cmFuc2l0aW9uOiB0cmFuc2Zvcm0gLjJzO1xyXG4gICAgICAgICAgfVxyXG5cclxuICAgICAgICAgID4ucmVhZC1tb3JlIHtcclxuICAgICAgICAgICAgcG9zaXRpb246IGFic29sdXRlO1xyXG4gICAgICAgICAgICB6LWluZGV4OiAzO1xyXG4gICAgICAgICAgICBib3R0b206IDA7XHJcbiAgICAgICAgICAgIHJpZ2h0OiAwO1xyXG4gICAgICAgICAgICBjb2xvcjogd2hpdGU7XHJcbiAgICAgICAgICAgIGZvbnQtc2l6ZTogMTFweDtcclxuICAgICAgICAgICAgcGFkZGluZzogMTBweCAyMHB4O1xyXG5cclxuICAgICAgICAgICAgQG1lZGlhIChtaW4td2lkdGg6ICRkZXNrdG9wKSB7XHJcbiAgICAgICAgICAgICAgZm9udC1zaXplOiBpbmhlcml0O1xyXG4gICAgICAgICAgICB9XHJcblxyXG4gICAgICAgICAgfVxyXG5cclxuICAgICAgICAgID4udGl0bGUtZGVzY3JpcHRpb24ge1xyXG4gICAgICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XHJcbiAgICAgICAgICAgIHotaW5kZXg6IDI7XHJcbiAgICAgICAgICAgIGNvbG9yOiB3aGl0ZTtcclxuICAgICAgICAgICAgd2lkdGg6IDEwMCU7XHJcbiAgICAgICAgICAgIGJvdHRvbTogMDtcclxuICAgICAgICAgICAgcGFkZGluZzogMjBweCAxNXB4IDMwcHggMTVweDtcclxuICAgICAgICAgICAgYmFja2dyb3VuZDogIzAwMDAwMGI4O1xyXG5cclxuXHJcbiAgICAgICAgICAgIEBtZWRpYSAobWluLXdpZHRoOiAkZGVza3RvcCkge1xyXG4gICAgICAgICAgICAgIHBhZGRpbmc6IDMwcHggMjBweCA0MHB4IDIwcHg7XHJcbiAgICAgICAgICAgIH1cclxuXHJcblxyXG4gICAgICAgICAgICA+LnRpdGxlIHtcclxuICAgICAgICAgICAgICBmb250LXNpemU6IDI3cHg7XHJcbiAgICAgICAgICAgICAgZm9udC13ZWlnaHQ6IDgwMDtcclxuICAgICAgICAgICAgICBtYXJnaW4tYm90dG9tOiA1cHg7XHJcblxyXG4gICAgICAgICAgICAgIEBtZWRpYSAobWluLXdpZHRoOiAkZGVza3RvcCkge1xyXG4gICAgICAgICAgICAgICAgbWFyZ2luLWJvdHRvbTogMTVweDtcclxuICAgICAgICAgICAgICAgIGZvbnQtc2l6ZTogMzRweDtcclxuICAgICAgICAgICAgICB9XHJcbiAgICAgICAgICAgIH1cclxuXHJcbiAgICAgICAgICAgID4uZGVzY3JpcHRpb24ge1xyXG4gICAgICAgICAgICAgIGZvbnQtc2l6ZTogMTVweDtcclxuICAgICAgICAgICAgICBsaW5lLWhlaWdodDogMjBweDtcclxuXHJcbiAgICAgICAgICAgICAgQG1lZGlhIChtaW4td2lkdGg6ICRkZXNrdG9wKSB7XHJcbiAgICAgICAgICAgICAgICBmb250LXNpemU6IDEzcHg7XHJcbiAgICAgICAgICAgICAgICBsaW5lLWhlaWdodDogMzBweDtcclxuXHJcbiAgICAgICAgICAgICAgfVxyXG4gICAgICAgICAgICB9XHJcbiAgICAgICAgICB9XHJcbiAgICAgICAgfVxyXG4gICAgICB9XHJcbiAgICB9XHJcbiAgfVxyXG59IiwiLmJ0bntcclxuICAgIGJhY2tncm91bmQ6ICRjb2xvci1wcmltYXJ5O1xyXG4gICAgY29sb3I6IHdoaXRlO1xyXG4gICAgZm9udC1zaXplOiAyNHB4O1xyXG4gICAgdGV4dC1hbGlnbjogbGVmdDtcclxuICAgIG1heC13aWR0aDogMzAwcHg7XHJcbiAgICBmb250LXdlaWdodDogODAwO1xyXG4gICAgYm9yZGVyOiBub25lO1xyXG4gICAgYm9yZGVyLXJhZGl1czogM3B4O1xyXG4gICAgcGFkZGluZzogMTVweCAzMHB4O1xyXG4gICAgdHJhbnNpdGlvbjogLjJzO1xyXG4gICAgY3Vyc29yOiBwb2ludGVyO1xyXG5cclxuICAgICY6aG92ZXJ7XHJcbiAgICAgICAgYmFja2dyb3VuZDogZGFya2VuKCRjb2xvci1wcmltYXJ5LCA1JSk7XHJcbiAgICB9XHJcbn0iLCIuZ3VpZGUtZGV0YWlsIHtcclxuICBwYWRkaW5nOiAxMHB4IDE1cHg7XHJcblxyXG4gIEBtZWRpYShtaW4td2lkdGg6ICRkZXNrdG9wKSB7XHJcbiAgICBwYWRkaW5nOiA1MHB4IDE1JTtcclxuICB9XHJcblxyXG4gID4uaGVhZGVyIHtcclxuICAgID4udGl0bGUge1xyXG4gICAgICBmb250LXNpemU6IDMwcHg7XHJcbiAgICAgIGxpbmUtaGVpZ2h0OiAzMHB4O1xyXG4gICAgICBtYXJnaW4tYm90dG9tOiAxMHB4O1xyXG4gICAgICBmb250LXdlaWdodDogODAwO1xyXG5cclxuICAgICAgQG1lZGlhKG1pbi13aWR0aDogJHRhYmxldCkge1xyXG4gICAgICAgIGZvbnQtc2l6ZTogMzVweDtcclxuICAgICAgICBsaW5lLWhlaWdodDogMzVweDtcclxuICAgICAgICBtYXJnaW4tYm90dG9tOiAxNXB4O1xyXG4gICAgICB9XHJcblxyXG4gICAgICBAbWVkaWEobWluLXdpZHRoOiAkZGVza3RvcCkge1xyXG4gICAgICAgIGZvbnQtc2l6ZTogNDJweDtcclxuICAgICAgICBsaW5lLWhlaWdodDogNDBweDtcclxuICAgICAgICBtYXJnaW4tYm90dG9tOiAyNXB4O1xyXG4gICAgICB9XHJcbiAgICB9XHJcblxyXG4gICAgPi5zdWJ0aXRsZSB7XHJcbiAgICAgIGZvbnQtc2l6ZTogMTVweDtcclxuICAgICAgY29sb3I6ICRjb2xvci1ncmF5O1xyXG4gICAgICB0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlO1xyXG4gICAgICBtYXJnaW4tYm90dG9tOiA1cHg7XHJcblxyXG4gICAgICBAbWVkaWEobWluLXdpZHRoOiAkdGFibGV0KSB7XHJcbiAgICAgICAgZm9udC1zaXplOiAxOHB4O1xyXG4gICAgICAgIG1hcmdpbi1ib3R0b206IDEwcHg7XHJcbiAgICAgIH1cclxuXHJcbiAgICAgIEBtZWRpYShtaW4td2lkdGg6ICRkZXNrdG9wKSB7XHJcbiAgICAgICAgZm9udC1zaXplOiAyMXB4O1xyXG4gICAgICAgIG1hcmdpbi1ib3R0b206IDIwcHg7XHJcbiAgICAgIH1cclxuICAgIH1cclxuXHJcbiAgICA+LnRpbWUge1xyXG4gICAgICBmb250LXNpemU6IDEzcHg7XHJcbiAgICAgIGNvbG9yOiAkY29sb3ItZ3JheTtcclxuXHJcbiAgICAgIEBtZWRpYShtaW4td2lkdGg6ICR0YWJsZXQpIHtcclxuICAgICAgICBmb250LXNpemU6IDE1cHg7XHJcbiAgICAgIH1cclxuXHJcbiAgICAgIEBtZWRpYShtaW4td2lkdGg6ICRkZXNrdG9wKSB7XHJcbiAgICAgICAgZm9udC1zaXplOiAxOHB4O1xyXG4gICAgICB9XHJcbiAgICB9XHJcbiAgfVxyXG5cclxuICA+LnVwcGVyLXRodW1iIHtcclxuICAgIGRpc3BsYXk6IGZsZXg7XHJcbiAgICBqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47XHJcbiAgICBhbGlnbi1pdGVtczogY2VudGVyO1xyXG4gICAgbWFyZ2luOiAzMHB4IDAgMzBweCAwO1xyXG5cclxuICAgID4ubGlzdGVuIHtcclxuICAgICAgZm9udC1zaXplOiAyMHB4O1xyXG4gICAgICBkaXNwbGF5OiBmbGV4O1xyXG4gICAgICBhbGlnbi1pdGVtczogY2VudGVyO1xyXG4gICAgICBjb2xvcjogZGFya2VuKCRjb2xvci1wcmltYXJ5LCA1JSk7XHJcbiAgICAgIHRyYW5zaXRpb246IGNvbG9yIC4ycztcclxuICAgICAgY3Vyc29yOiBwb2ludGVyO1xyXG5cclxuICAgICAgJjpob3ZlcntcclxuICAgICAgICBjb2xvcjogZGFya2VuKCRjb2xvci1wcmltYXJ5LCAyMCUpO1xyXG4gICAgICB9XHJcblxyXG4gICAgICA+LnRleHQge1xyXG4gICAgICAgIGZvbnQtd2VpZ2h0OiA2MDA7XHJcbiAgICAgICAgbWFyZ2luLXJpZ2h0OiAxMHB4O1xyXG4gICAgICB9XHJcblxyXG4gICAgICA+LnBsYXkge1xyXG4gICAgICAgIGZvbnQtc2l6ZTogMjhweDtcclxuICAgICAgfVxyXG4gICAgfVxyXG5cclxuICAgID4uc2hhcmV7XHJcbiAgICAgIGZvbnQtc2l6ZTogMjhweDtcclxuICAgICAgXHJcbiAgICAgID4uaWNvbntcclxuICAgICAgICBtYXJnaW4tbGVmdDogMTBweDtcclxuICAgICAgICBcclxuICAgICAgdHJhbnNpdGlvbjogY29sb3IgLjJzO1xyXG5cclxuICAgICAgJjpob3ZlcntcclxuICAgICAgICBjb2xvcjogJGNvbG9yLXByaW1hcnk7XHJcbiAgICAgIH1cclxuICAgIH1cclxuICAgIH1cclxuICB9XHJcblxyXG4gID4udGh1bWIge1xyXG4gICAgbWFyZ2luLXRvcDogMjBweDtcclxuICAgIG1hcmdpbi1ib3R0b206IDIwcHg7XHJcblxyXG4gICAgPi5pbWctd3JhcHBlciB7XHJcbiAgICAgIHBvc2l0aW9uOiByZWxhdGl2ZTtcclxuICAgICAgaGVpZ2h0OiAyNTBweDtcclxuICAgICAgb3ZlcmZsb3c6IGhpZGRlbjtcclxuXHJcbiAgICAgID4uaW1nIHtcclxuICAgICAgICB0b3A6IDUwJTtcclxuICAgICAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTUwJSk7XHJcbiAgICAgICAgcG9zaXRpb246IGFic29sdXRlO1xyXG4gICAgICAgIHdpZHRoOiAxMDAlO1xyXG4gICAgICAgIG1pbi1oZWlnaHQ6IDEwMCU7XHJcbiAgICAgIH1cclxuICAgIH1cclxuXHJcbiAgICA+LmRlc2NyaXB0aW9uIHtcclxuICAgICAgbWFyZ2luLXRvcDogN3B4O1xyXG4gICAgICBmb250LXNpemU6IDEzcHg7XHJcbiAgICAgIGNvbG9yOiAkY29sb3ItZ3JheTtcclxuICAgIH1cclxuICB9XHJcblxyXG4gIC5zbWFsbC10aXRsZXtcclxuICAgIGZvbnQtc2l6ZTogMjJweDtcclxuICAgIGZvbnQtd2VpZ2h0OiA4MDA7XHJcbiAgICBtYXJnaW4tYm90dG9tOiAyNXB4O1xyXG4gICAgbWFyZ2luLXRvcDogNTBweDtcclxuICB9XHJcblxyXG4gID4ucmVmZXJlbmNlc3tcclxuICAgIC5saW5re1xyXG4gICAgICBjb2xvcjogJGNvbG9yLXByaW1hcnk7XHJcbiAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jaztcclxuICAgICAgbWFyZ2luLWJvdHRvbTogMTVweDtcclxuICAgICAgY3Vyc29yOiBwb2ludGVyO1xyXG4gICAgICBmb250LXNpemU6IDEycHg7XHJcbiAgICB9XHJcbiAgfVxyXG5cclxuICA+Lmd1aWRlIHtcclxuICAgID4ucGFyYWdyYXBoIHtcclxuICAgICAgbGluZS1oZWlnaHQ6IDI2cHg7XHJcbiAgICAgIG1hcmdpbi1ib3R0b206IDIwcHg7XHJcblxyXG4gICAgICAmLi1pcy1zdGVwe1xyXG4gICAgICAgIG1hcmdpbi1ib3R0b206IDA7XHJcbiAgICAgIH1cclxuXHJcbiAgICAgICYuLWlzLWxhc3Qtc3RlcHtcclxuICAgICAgICBtYXJnaW4tYm90dG9tOiAyMHB4O1xyXG4gICAgICB9XHJcblxyXG4gICAgICA+LnN0ZXAge1xyXG4gICAgICAgIGZvbnQtd2VpZ2h0OiA4MDA7XHJcbiAgICAgICAgY29sb3I6ICRjb2xvci1wcmltYXJ5O1xyXG4gICAgICAgIGZvbnQtc2l6ZTogMjBweDtcclxuICAgICAgICBtYXJnaW4tcmlnaHQ6IDVweDtcclxuICAgICAgfVxyXG4gICAgfVxyXG4gIH1cclxuXHJcbiAgPi5zaGFyZS1uZXh0e1xyXG4gICAgZGlzcGxheTogZmxleDtcclxuICAgIGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2VlbjtcclxuICAgIGFsaWduLWl0ZW1zOiBmbGV4LXN0YXJ0O1xyXG4gICAgbWFyZ2luLXRvcDogMzBweDtcclxuXHJcbiAgICA+LnNoYXJle1xyXG4gICAgPi5zbWFsbC10aXRsZXtcclxubWFyZ2luLXRvcDogMDtcclxuICAgIH1cclxuICB9XHJcbiAgfVxyXG59IiwiLl90ZXh0LWNlbnRlcntcclxuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcclxufSJdfQ== */", '', '']];
    /***/
  },

  /***/
  "./node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js":
  /*!****************************************************************************!*\
    !*** ./node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js ***!
    \****************************************************************************/

  /*! no static exports found */

  /***/
  function node_modulesStyleLoaderDistRuntimeInjectStylesIntoStyleTagJs(module, exports, __webpack_require__) {
    "use strict";

    var stylesInDom = {};

    var isOldIE = function isOldIE() {
      var memo;
      return function memorize() {
        if (typeof memo === 'undefined') {
          // Test for IE <= 9 as proposed by Browserhacks
          // @see http://browserhacks.com/#hack-e71d8692f65334173fee715c222cb805
          // Tests for existence of standard globals is to allow style-loader
          // to operate correctly into non-standard environments
          // @see https://github.com/webpack-contrib/style-loader/issues/177
          memo = Boolean(window && document && document.all && !window.atob);
        }

        return memo;
      };
    }();

    var getTarget = function getTarget() {
      var memo = {};
      return function memorize(target) {
        if (typeof memo[target] === 'undefined') {
          var styleTarget = document.querySelector(target); // Special case to return head of iframe instead of iframe itself

          if (window.HTMLIFrameElement && styleTarget instanceof window.HTMLIFrameElement) {
            try {
              // This will throw an exception if access to iframe is blocked
              // due to cross-origin restrictions
              styleTarget = styleTarget.contentDocument.head;
            } catch (e) {
              // istanbul ignore next
              styleTarget = null;
            }
          }

          memo[target] = styleTarget;
        }

        return memo[target];
      };
    }();

    function listToStyles(list, options) {
      var styles = [];
      var newStyles = {};

      for (var i = 0; i < list.length; i++) {
        var item = list[i];
        var id = options.base ? item[0] + options.base : item[0];
        var css = item[1];
        var media = item[2];
        var sourceMap = item[3];
        var part = {
          css: css,
          media: media,
          sourceMap: sourceMap
        };

        if (!newStyles[id]) {
          styles.push(newStyles[id] = {
            id: id,
            parts: [part]
          });
        } else {
          newStyles[id].parts.push(part);
        }
      }

      return styles;
    }

    function addStylesToDom(styles, options) {
      for (var i = 0; i < styles.length; i++) {
        var item = styles[i];
        var domStyle = stylesInDom[item.id];
        var j = 0;

        if (domStyle) {
          domStyle.refs++;

          for (; j < domStyle.parts.length; j++) {
            domStyle.parts[j](item.parts[j]);
          }

          for (; j < item.parts.length; j++) {
            domStyle.parts.push(addStyle(item.parts[j], options));
          }
        } else {
          var parts = [];

          for (; j < item.parts.length; j++) {
            parts.push(addStyle(item.parts[j], options));
          }

          stylesInDom[item.id] = {
            id: item.id,
            refs: 1,
            parts: parts
          };
        }
      }
    }

    function insertStyleElement(options) {
      var style = document.createElement('style');

      if (typeof options.attributes.nonce === 'undefined') {
        var nonce = true ? __webpack_require__.nc : undefined;

        if (nonce) {
          options.attributes.nonce = nonce;
        }
      }

      Object.keys(options.attributes).forEach(function (key) {
        style.setAttribute(key, options.attributes[key]);
      });

      if (typeof options.insert === 'function') {
        options.insert(style);
      } else {
        var target = getTarget(options.insert || 'head');

        if (!target) {
          throw new Error("Couldn't find a style target. This probably means that the value for the 'insert' parameter is invalid.");
        }

        target.appendChild(style);
      }

      return style;
    }

    function removeStyleElement(style) {
      // istanbul ignore if
      if (style.parentNode === null) {
        return false;
      }

      style.parentNode.removeChild(style);
    }
    /* istanbul ignore next  */


    var replaceText = function replaceText() {
      var textStore = [];
      return function replace(index, replacement) {
        textStore[index] = replacement;
        return textStore.filter(Boolean).join('\n');
      };
    }();

    function applyToSingletonTag(style, index, remove, obj) {
      var css = remove ? '' : obj.css; // For old IE

      /* istanbul ignore if  */

      if (style.styleSheet) {
        style.styleSheet.cssText = replaceText(index, css);
      } else {
        var cssNode = document.createTextNode(css);
        var childNodes = style.childNodes;

        if (childNodes[index]) {
          style.removeChild(childNodes[index]);
        }

        if (childNodes.length) {
          style.insertBefore(cssNode, childNodes[index]);
        } else {
          style.appendChild(cssNode);
        }
      }
    }

    function applyToTag(style, options, obj) {
      var css = obj.css;
      var media = obj.media;
      var sourceMap = obj.sourceMap;

      if (media) {
        style.setAttribute('media', media);
      }

      if (sourceMap && btoa) {
        css += "\n/*# sourceMappingURL=data:application/json;base64,".concat(btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))), " */");
      } // For old IE

      /* istanbul ignore if  */


      if (style.styleSheet) {
        style.styleSheet.cssText = css;
      } else {
        while (style.firstChild) {
          style.removeChild(style.firstChild);
        }

        style.appendChild(document.createTextNode(css));
      }
    }

    var singleton = null;
    var singletonCounter = 0;

    function addStyle(obj, options) {
      var style;
      var update;
      var remove;

      if (options.singleton) {
        var styleIndex = singletonCounter++;
        style = singleton || (singleton = insertStyleElement(options));
        update = applyToSingletonTag.bind(null, style, styleIndex, false);
        remove = applyToSingletonTag.bind(null, style, styleIndex, true);
      } else {
        style = insertStyleElement(options);
        update = applyToTag.bind(null, style, options);

        remove = function remove() {
          removeStyleElement(style);
        };
      }

      update(obj);
      return function updateStyle(newObj) {
        if (newObj) {
          if (newObj.css === obj.css && newObj.media === obj.media && newObj.sourceMap === obj.sourceMap) {
            return;
          }

          update(obj = newObj);
        } else {
          remove();
        }
      };
    }

    module.exports = function (list, options) {
      options = options || {};
      options.attributes = typeof options.attributes === 'object' ? options.attributes : {}; // Force single-tag solution on IE6-9, which has a hard limit on the # of <style>
      // tags it will allow on a page

      if (!options.singleton && typeof options.singleton !== 'boolean') {
        options.singleton = isOldIE();
      }

      var styles = listToStyles(list, options);
      addStylesToDom(styles, options);
      return function update(newList) {
        var mayRemove = [];

        for (var i = 0; i < styles.length; i++) {
          var item = styles[i];
          var domStyle = stylesInDom[item.id];

          if (domStyle) {
            domStyle.refs--;
            mayRemove.push(domStyle);
          }
        }

        if (newList) {
          var newStyles = listToStyles(newList, options);
          addStylesToDom(newStyles, options);
        }

        for (var _i = 0; _i < mayRemove.length; _i++) {
          var _domStyle = mayRemove[_i];

          if (_domStyle.refs === 0) {
            for (var j = 0; j < _domStyle.parts.length; j++) {
              _domStyle.parts[j]();
            }

            delete stylesInDom[_domStyle.id];
          }
        }
      };
    };
    /***/

  },

  /***/
  "./src/styles.scss":
  /*!*************************!*\
    !*** ./src/styles.scss ***!
    \*************************/

  /*! no static exports found */

  /***/
  function srcStylesScss(module, exports, __webpack_require__) {
    var content = __webpack_require__(
    /*! !../node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!../node_modules/postcss-loader/src??embedded!../node_modules/sass-loader/dist/cjs.js??ref--13-3!./styles.scss */
    "./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src/index.js?!./node_modules/sass-loader/dist/cjs.js?!./src/styles.scss");

    if (typeof content === 'string') {
      content = [[module.i, content, '']];
    }

    var options = {};
    options.insert = "head";
    options.singleton = false;

    var update = __webpack_require__(
    /*! ../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js */
    "./node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js")(content, options);

    if (content.locals) {
      module.exports = content.locals;
    }
    /***/

  },

  /***/
  3:
  /*!*******************************!*\
    !*** multi ./src/styles.scss ***!
    \*******************************/

  /*! no static exports found */

  /***/
  function _(module, exports, __webpack_require__) {
    module.exports = __webpack_require__(
    /*! C:\Users\Takara\Google Drive\Projetos\8dobem\src\styles.scss */
    "./src/styles.scss");
    /***/
  }
}, [[3, "runtime"]]]);
//# sourceMappingURL=styles-es5.js.map